/**
 * Mock agent data for testing and demos.
 */
export const MOCK_AGENTS = [
  {
    id: 'agent-1',
    organizationId: 'demo-org',
    name: 'Customer Support Bot',
    slug: 'customer-support-bot',
    description: 'Handles tier-1 customer inquiries and routes complex issues.',
    status: 'ACTIVE' as const,
    modelProvider: 'OPENAI' as const,
    modelName: 'gpt-4o-mini',
    modelConfig: { temperature: 0.7 },
    systemPrompt: 'You are a helpful customer support assistant.',
    toolChoice: 'auto' as const,
    maxIterations: 10,
    timeoutMs: 120000,
    version: '1.0.0',
    tags: ['support', 'tier-1'],
    createdAt: new Date('2024-01-15T10:00:00Z'),
    updatedAt: new Date('2024-03-20T14:30:00Z'),
  },
  {
    id: 'agent-2',
    organizationId: 'demo-org',
    name: 'Code Review Assistant',
    slug: 'code-review-assistant',
    description: 'Reviews pull requests and provides actionable feedback.',
    status: 'ACTIVE' as const,
    modelProvider: 'ANTHROPIC' as const,
    modelName: 'claude-sonnet-4-20250514',
    modelConfig: { temperature: 0.3 },
    systemPrompt: 'You are a code review expert.',
    toolChoice: 'auto' as const,
    maxIterations: 15,
    timeoutMs: 180000,
    version: '2.1.0',
    tags: ['code', 'review', 'dev'],
    createdAt: new Date('2024-02-10T09:00:00Z'),
    updatedAt: new Date('2024-04-05T11:15:00Z'),
  },
  {
    id: 'agent-3',
    organizationId: 'demo-org',
    name: 'Data Analyst',
    slug: 'data-analyst',
    description: 'Queries databases and generates insights from data.',
    status: 'PAUSED' as const,
    modelProvider: 'OPENAI' as const,
    modelName: 'gpt-4o',
    modelConfig: { temperature: 0.5 },
    systemPrompt: 'You are a data analyst expert in SQL and analytics.',
    toolChoice: 'required' as const,
    maxIterations: 20,
    timeoutMs: 300000,
    version: '1.2.0',
    tags: ['data', 'analytics', 'sql'],
    createdAt: new Date('2024-03-01T08:00:00Z'),
    updatedAt: new Date('2024-04-10T16:45:00Z'),
  },
  {
    id: 'agent-4',
    organizationId: 'demo-org',
    name: 'Meeting Scheduler',
    slug: 'meeting-scheduler',
    description: 'Schedules meetings and manages calendar conflicts.',
    status: 'DRAFT' as const,
    modelProvider: 'GOOGLE' as const,
    modelName: 'gemini-2.0-flash',
    modelConfig: { temperature: 0.2 },
    systemPrompt: 'You help schedule and organize meetings efficiently.',
    toolChoice: 'auto' as const,
    maxIterations: 5,
    timeoutMs: 60000,
    version: '0.1.0',
    tags: ['calendar', 'scheduling'],
    createdAt: new Date('2024-04-01T12:00:00Z'),
    updatedAt: new Date('2024-04-01T12:00:00Z'),
  },
];
