/**
 * CICD workflow templates.
 *
 * Templates for generating GitHub Actions workflow files.
 */

export interface WorkflowConfig {
  name: string;
  mode: 'validate' | 'impact' | 'both';
  checks: string[];
  failOnWarnings: boolean;
  failOnBreaking: boolean;
  prComment: boolean;
  uploadSarif: boolean;
  workingDirectory: string;
  nodeVersion: string;
  bunVersion: string;
}

const DEFAULT_CONFIG: WorkflowConfig = {
  name: 'ContractSpec CI',
  mode: 'validate',
  checks: ['all'],
  failOnWarnings: false,
  failOnBreaking: true,
  prComment: true,
  uploadSarif: true,
  workingDirectory: '.',
  nodeVersion: '20',
  bunVersion: 'latest',
};

/**
 * Generate validate workflow content.
 */
function generateValidateJob(config: WorkflowConfig): string {
  return `
  validate:
    name: Validate Contracts
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${config.bunVersion}

      - name: Install dependencies
        run: bun install
        working-directory: ${config.workingDirectory}

      - name: Run ContractSpec Checks
        uses: lssm-tech/contractspec-action@v1
        with:
          mode: validate
          checks: '${config.checks.join(',')}'
          fail-on-warnings: '${config.failOnWarnings}'
          upload-sarif: '${config.uploadSarif}'
          working-directory: ${config.workingDirectory}`;
}

/**
 * Generate impact detection job content.
 */
function generateImpactJob(config: WorkflowConfig): string {
  return `
  impact:
    name: Detect Breaking Changes
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      contents: read
      pull-requests: write
      checks: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${config.bunVersion}

      - name: Install dependencies
        run: bun install
        working-directory: ${config.workingDirectory}

      - name: Detect Contract Impact
        uses: lssm-tech/contractspec-action@v1
        with:
          mode: impact
          baseline: \${{ github.event.pull_request.base.ref }}
          pr-comment: '${config.prComment}'
          fail-on-breaking: '${config.failOnBreaking}'
          working-directory: ${config.workingDirectory}
          github-token: \${{ secrets.GITHUB_TOKEN }}`;
}

/**
 * Generate full workflow file content.
 */
export function generateWorkflow(config: Partial<WorkflowConfig> = {}): string {
  const fullConfig: WorkflowConfig = { ...DEFAULT_CONFIG, ...config };

  let jobs = '';

  if (fullConfig.mode === 'validate' || fullConfig.mode === 'both') {
    jobs += generateValidateJob(fullConfig);
  }

  if (fullConfig.mode === 'impact' || fullConfig.mode === 'both') {
    jobs += generateImpactJob(fullConfig);
  }

  return `# ContractSpec CI Workflow
# Generated by: contractspec cicd install
# Docs: https://contractspec.lssm.tech/docs/cicd

name: ${fullConfig.name}

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:${jobs}
`;
}

/**
 * Default workflow for quick setup.
 */
export function generateQuickWorkflow(): string {
  return generateWorkflow({ mode: 'both' });
}

/**
 * Minimal validate-only workflow.
 */
export function generateValidateOnlyWorkflow(): string {
  return generateWorkflow({ mode: 'validate' });
}
