import { defineFeature } from '@contractspec/lib.contracts-spec/features';

export const ContractsIntegrationsFeature = defineFeature({
	meta: {
		key: 'libs.contracts-integrations',
		version: '1.0.0',
		title: 'Contracts Integrations',
		description: 'Integration contract definitions for external services',
		domain: 'contracts-integrations',
		owners: ['@contractspec-core'],
		tags: ['package', 'libs', 'contracts-integrations'],
		stability: 'experimental',
	},
	operations: [
		{ key: 'health.activities.list', version: '1.0.0' },
		{ key: 'health.activities.sync', version: '1.0.0' },
		{ key: 'health.biometrics.list', version: '1.0.0' },
		{ key: 'health.biometrics.sync', version: '1.0.0' },
		{ key: 'health.nutrition.list', version: '1.0.0' },
		{ key: 'health.nutrition.sync', version: '1.0.0' },
		{ key: 'health.sleep.list', version: '1.0.0' },
		{ key: 'health.sleep.sync', version: '1.0.0' },
		{ key: 'health.webhooks.ingest', version: '1.0.0' },
		{ key: 'health.workouts.list', version: '1.0.0' },
		{ key: 'health.workouts.sync', version: '1.0.0' },
		{ key: 'meeting-recorder.meetings.list', version: '1.0.0' },
		{ key: 'meeting-recorder.meetings.get', version: '1.0.0' },
		{ key: 'meeting-recorder.transcripts.get', version: '1.0.0' },
		{ key: 'meeting-recorder.transcripts.sync', version: '1.0.0' },
		{ key: 'meeting-recorder.webhooks.ingest', version: '1.0.0' },
		{ key: 'openbanking.accounts.list', version: '1.0.0' },
		{ key: 'openbanking.accounts.get', version: '1.0.0' },
		{ key: 'openbanking.accounts.sync', version: '1.0.0' },
		{ key: 'openbanking.balances.get', version: '1.0.0' },
		{ key: 'openbanking.balances.refresh', version: '1.0.0' },
		{ key: 'openbanking.transactions.list', version: '1.0.0' },
		{ key: 'openbanking.transactions.sync', version: '1.0.0' },
		{ key: 'integrations.connection.create', version: '1.0.0' },
		{ key: 'integrations.connection.update', version: '1.0.0' },
		{ key: 'integrations.connection.delete', version: '1.0.0' },
		{ key: 'integrations.connection.list', version: '1.0.0' },
		{ key: 'integrations.connection.test', version: '1.0.0' },
	],
});
