/**
 * Skeleton event template.
 *
 * Generates a minimal event spec stub with in_creation stability.
 */

import type { SpecGenerationContext } from '../../services/fix/types';

import { toPascalCase, generateMetaProperties } from './utils';

/**
 * Generate a minimal event spec skeleton.
 */
export function generateSkeletonEvent(ctx: SpecGenerationContext): string {
  const namePart = ctx.key.split('.').pop() || 'Unknown';
  const specVarName = toPascalCase(namePart) + 'EventSpec';
  const payloadName = specVarName.replace('Spec', 'Payload');

  const metaProps = generateMetaProperties(ctx);

  return `/**
 * Event: ${ctx.key}
 *
 * Skeleton spec generated by ContractSpec fix command.
 * Status: in_creation - Requires implementation
 *
 * Referenced by feature: ${ctx.featureKey || 'unknown'}
 */

import { defineEvent } from '@contractspec/lib.contracts-spec';
import { ScalarTypeEnum, SchemaModel } from '@contractspec/lib.schema';

// TODO: Define event payload schema
export const ${payloadName} = new SchemaModel({
  name: '${payloadName}',
  description: 'Payload for ${ctx.key} event',
  fields: {
    // Add your payload fields here
    // Example:
    // entityId: { type: ScalarTypeEnum.String_unsecure(), isOptional: false },
    // timestamp: { type: ScalarTypeEnum.DateTime(), isOptional: false },
  },
});

export const ${specVarName} = defineEvent({
  meta: {
    ${metaProps}
  },

  payload: ${payloadName},

  // TODO: Specify PII fields if any
  // piiFields: ['user.email'],

  // TODO: Specify retention policy
  // retention: {
  //   days: 365,
  //   policy: 'archive',
  // },
});
`;
}
