/**
 * Skeleton event template.
 *
 * Generates a minimal event spec stub with in_creation stability.
 */

import type { SpecGenerationContext } from '../../services/fix/types';

/**
 * Convert a string to PascalCase.
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_.]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/**
 * Generate a minimal event spec skeleton.
 */
export function generateSkeletonEvent(ctx: SpecGenerationContext): string {
  const namePart = ctx.key.split('.').pop() || 'Unknown';
  const specVarName = toPascalCase(namePart) + 'EventSpec';
  const payloadName = specVarName.replace('Spec', 'Payload');

  const owners = ctx.enrichment?.owners?.length
    ? ctx.enrichment.owners.map((o) => `'${o}'`).join(', ')
    : "'@team'";

  const tags = ctx.enrichment?.tags?.length
    ? ctx.enrichment.tags.map((t) => `'${t}'`).join(', ')
    : '';

  const description = ctx.description || `TODO: Add description for ${ctx.key}`;

  return `/**
 * Event: ${ctx.key}
 *
 * Skeleton spec generated by ContractSpec fix command.
 * Status: in_creation - Requires implementation
 *
 * Referenced by feature: ${ctx.featureKey || 'unknown'}
 */

import { defineEvent } from '@contractspec/lib.contracts';
import { ScalarTypeEnum, SchemaModel } from '@contractspec/lib.schema';

// TODO: Define event payload schema
export const ${payloadName} = new SchemaModel({
  name: '${payloadName}',
  description: 'Payload for ${ctx.key} event',
  fields: {
    // Add your payload fields here
    // Example:
    // entityId: { type: ScalarTypeEnum.String_unsecure(), isOptional: false },
    // timestamp: { type: ScalarTypeEnum.DateTime(), isOptional: false },
  },
});

export const ${specVarName} = defineEvent({
  meta: {
    key: '${ctx.key}',
    version: '${ctx.version}',
    stability: '${ctx.stability}',
    owners: [${owners}],
    tags: [${tags}],
    description: '${description}',
  },

  payload: ${payloadName},

  // TODO: Specify PII fields if any
  // piiFields: ['user.email'],

  // TODO: Specify retention policy
  // retention: {
  //   days: 365,
  //   policy: 'archive',
  // },
});
`;
}
