/**
 * Skeleton capability template.
 *
 * Generates a minimal capability spec stub with in_creation stability.
 */

import type { SpecGenerationContext } from '../../services/fix/types';

/**
 * Convert a string to PascalCase.
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_.]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/**
 * Generate a minimal capability spec skeleton.
 */
export function generateSkeletonCapability(ctx: SpecGenerationContext): string {
  const namePart = ctx.key.split('.').pop() || 'Unknown';
  const specVarName = toPascalCase(namePart) + 'Spec';
  const dataSchemaName = specVarName.replace('Spec', 'Data');

  const owners = ctx.enrichment?.owners?.length
    ? ctx.enrichment.owners.map((o) => `'${o}'`).join(', ')
    : "'@team'";

  const tags = ctx.enrichment?.tags?.length
    ? ctx.enrichment.tags.map((t) => `'${t}'`).join(', ')
    : '';

  const description = ctx.description || `TODO: Add description for ${ctx.key}`;
  const goal = ctx.enrichment?.goal || 'TODO: Define the capability goal';

  return `/**
 * Capability: ${ctx.key}
 *
 * Skeleton spec generated by ContractSpec fix command.
 * Status: in_creation - Requires implementation
 *
 * Referenced by feature: ${ctx.featureKey || 'unknown'}
 */

import { defineCapability } from '@contractspec/lib.contracts';
import { ScalarTypeEnum, SchemaModel } from '@contractspec/lib.schema';

// TODO: Define capability data schema
export const ${dataSchemaName} = new SchemaModel({
  name: '${dataSchemaName}',
  description: 'Data model for ${ctx.key}',
  fields: {
    // Add your data fields here
    // Example:
    // isEnabled: { type: ScalarTypeEnum.Boolean(), isOptional: false },
  },
});

export const ${specVarName} = defineCapability({
  meta: {
    key: '${ctx.key}',
    version: '${ctx.version}',
    stability: '${ctx.stability}',
    owners: [${owners}],
    tags: [${tags}],
    description: '${description}',
    goal: '${goal}',
  },

  data: ${dataSchemaName},

  actions: {
    // TODO: Define actions provided by this capability
    // exampleAction: {
    //   description: 'Perform an example action',
    //   input: SomeInputSchema,
    //   output: SomeOutputSchema,
    // },
  },
});
`;
}
