/**
 * Skeleton presentation template.
 *
 * Generates a minimal presentation spec stub with in_creation stability.
 */

import type { SpecGenerationContext } from '../../services/fix/types';

/**
 * Convert a string to PascalCase.
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_.]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/**
 * Infer presentation kind from key name.
 */
function inferPresentationKind(
  key: string
): 'web_component' | 'markdown' | 'data' {
  const lowerKey = key.toLowerCase();

  if (
    lowerKey.includes('doc') ||
    lowerKey.includes('guide') ||
    lowerKey.includes('readme')
  ) {
    return 'markdown';
  }

  if (
    lowerKey.includes('data') ||
    lowerKey.includes('api') ||
    lowerKey.includes('export')
  ) {
    return 'data';
  }

  return 'web_component';
}

/**
 * Generate a minimal presentation spec skeleton.
 */
export function generateSkeletonPresentation(
  ctx: SpecGenerationContext
): string {
  const namePart = ctx.key.split('.').pop() || 'Unknown';
  const specVarName = toPascalCase(namePart) + 'PresentationSpec';
  const presentationKind = inferPresentationKind(ctx.key);

  const owners = ctx.enrichment?.owners?.length
    ? ctx.enrichment.owners.map((o) => `'${o}'`).join(', ')
    : "'@team'";

  const tags = ctx.enrichment?.tags?.length
    ? ctx.enrichment.tags.map((t) => `'${t}'`).join(', ')
    : '';

  const description = ctx.description || `TODO: Add description for ${ctx.key}`;

  return `/**
 * Presentation: ${ctx.key}
 *
 * Skeleton spec generated by ContractSpec fix command.
 * Status: in_creation - Requires implementation
 *
 * Referenced by feature: ${ctx.featureKey || 'unknown'}
 */

import { definePresentation } from '@contractspec/lib.contracts';

export const ${specVarName} = definePresentation({
  meta: {
    key: '${ctx.key}',
    version: '${ctx.version}',
    stability: '${ctx.stability}',
    owners: [${owners}],
    tags: [${tags}],
    description: '${description}',
  },

  kind: '${presentationKind}',

  // TODO: Define content structure
  content: {
    // For web_component:
    // component: 'MyComponent',
    // props: {},

    // For markdown:
    // template: '# Title\\n\\nContent here...',

    // For data:
    // schema: {},
  },

  // TODO: Define targets (platforms where this renders)
  targets: ['web'],

  // TODO: Define accessibility requirements
  // a11y: {
  //   ariaLabel: '${ctx.key} presentation',
  //   focusable: true,
  // },
});
`;
}
