/**
 * Skeleton capability template.
 *
 * Generates a minimal capability spec stub with in_creation stability.
 */

import type { SpecGenerationContext } from '../../services/fix/types';

/**
 * Convert a string to PascalCase.
 */
function toPascalCase(str: string): string {
  return str
    .split(/[-_.]/)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/**
 * Generate a minimal capability spec skeleton.
 */
export function generateSkeletonCapability(ctx: SpecGenerationContext): string {
  const namePart = ctx.key.split('.').pop() || 'Unknown';
  const specVarName = toPascalCase(namePart) + 'Spec';
  
  const owners = ctx.enrichment?.owners?.length
    ? ctx.enrichment.owners.map((o) => `'${o}'`).join(', ')
    : "'@team'";

  const tags = ctx.enrichment?.tags?.length
    ? ctx.enrichment.tags.map((t) => `'${t}'`).join(', ')
    : '';

  const description = ctx.description || `TODO: Add description for ${ctx.key}`;
  const goal = ctx.enrichment?.goal || 'TODO: Define the capability goal';

  return `/**
 * Capability: ${ctx.key}
 *
 * Skeleton spec generated by ContractSpec fix command.
 * Status: in_creation - Requires implementation
 *
 * Referenced by feature: ${ctx.featureKey || 'unknown'}
 */

import { defineCapability } from '@contractspec/lib.contracts';

export const ${specVarName} = defineCapability({
  meta: {
    key: '${ctx.key}',
    version: '${ctx.version}',
    stability: '${ctx.stability}',
    kind: 'api', // Default kind, change to event|data|ui|integration as needed
    owners: [${owners}],
    tags: [${tags}],
    description: '${description}',
    goal: '${goal}',
  },

  provides: [
    // TODO: Define surfaces provided by this capability
    // example:
    // {
    //   surface: 'operation',
    //   key: 'some.operation',
    //   version: '1.0.0',
    //   description: 'Provides some operation',
    // }
  ],

  requires: [
    // TODO: Define requirements
    // example:
    // {
    //   key: 'other.capability',
    //   version: '1.0.0',
    //   optional: false,
    // }
  ],
});
`;
}
