/**
 * Skeleton capability template.
 *
 * Generates a minimal capability spec stub with in_creation stability.
 */

import type { SpecGenerationContext } from '../../services/fix/types';

import { toPascalCase, generateMetaProperties } from './utils';

export function generateSkeletonCapability(ctx: SpecGenerationContext): string {
  const namePart = ctx.key.split('.').pop() || 'Unknown';
  const specVarName = toPascalCase(namePart) + 'Spec';

  const metaProps = generateMetaProperties(ctx, {
    kind: "'api'", // Default kind, quoted
  });

  return `/**
 * Capability: ${ctx.key}
 *
 * Skeleton spec generated by ContractSpec fix command.
 * Status: in_creation - Requires implementation
 *
 * Referenced by feature: ${ctx.featureKey || 'unknown'}
 */

import { defineCapability } from '@contractspec/lib.contracts';

export const ${specVarName} = defineCapability({
  meta: {
    ${metaProps}
  },

  provides: [
    // TODO: Define surfaces provided by this capability
    // example:
    // {
    //   surface: 'operation',
    //   key: 'some.operation',
    //   version: '1.0.0',
    //   description: 'Provides some operation',
    // }
  ],

  requires: [
    // TODO: Define requirements
    // example:
    // {
    //   key: 'other.capability',
    //   version: '1.0.0',
    //   optional: false,
    // }
  ],
});
`;
}
