/**
 * Skeleton presentation template.
 *
 * Generates a minimal presentation spec stub with in_creation stability.
 */

import type { SpecGenerationContext } from '../../services/fix/types';

import { toPascalCase, generateMetaProperties } from './utils';

/**
 * Infer presentation kind from key name.
 */
function inferPresentationKind(
  key: string
): 'web_component' | 'markdown' | 'data' {
  const lowerKey = key.toLowerCase();

  if (
    lowerKey.includes('doc') ||
    lowerKey.includes('guide') ||
    lowerKey.includes('readme')
  ) {
    return 'markdown';
  }

  if (
    lowerKey.includes('data') ||
    lowerKey.includes('api') ||
    lowerKey.includes('export')
  ) {
    return 'data';
  }

  return 'web_component';
}

/**
 * Generate a minimal presentation spec skeleton.
 */
export function generateSkeletonPresentation(
  ctx: SpecGenerationContext
): string {
  const namePart = ctx.key.split('.').pop() || 'Unknown';
  const specVarName = toPascalCase(namePart) + 'PresentationSpec';
  const presentationKind = inferPresentationKind(ctx.key);

  const metaProps = generateMetaProperties(ctx);

  return `/**
 * Presentation: ${ctx.key}
 *
 * Skeleton spec generated by ContractSpec fix command.
 * Status: in_creation - Requires implementation
 *
 * Referenced by feature: ${ctx.featureKey || 'unknown'}
 */

import { definePresentation } from '@contractspec/lib.contracts';

export const ${specVarName} = definePresentation({
  meta: {
    ${metaProps}
  },

  kind: '${presentationKind}',

  // TODO: Define content structure
  content: {
    // For web_component:
    // component: 'MyComponent',
    // props: {},
    
    // For markdown:
    // template: '# Title\\n\\nContent here...',

    // For data:
    // schema: {},
  },

  // TODO: Define targets (platforms where this renders)
  targets: ['react', 'markdown'],

  // TODO: Define accessibility requirements
  // a11y: {
  //   ariaLabel: '${ctx.key} presentation',
  //   focusable: true,
  // },
});
`;
}
