/**
 * Forms exporter - exports FormSpec to OpenAPI extensions.
 */
import type { FormRegistry, Stability } from '@contractspec/lib.contracts';
import type { AnySchemaModel } from '@contractspec/lib.schema';
import { z } from 'zod';
import type { GeneratedRegistryCode } from '../types';

type OpenApiSchemaObject = Record<string, unknown>;

/**
 * Exported form structure for OpenAPI extensions.
 */
export interface ExportedForm {
  key: string;
  version: string;
  description: string;
  stability: Stability;
  owners?: string[];
  fields: unknown[];
  model: OpenApiSchemaObject | null;
  actions?: unknown[];
}

/**
 * Export forms to OpenAPI extension format.
 */
export function exportForms(registry: FormRegistry): ExportedForm[] {
  return registry.list().map((form) => ({
    key: form.meta.key,
    version: form.meta.version,
    description: form.meta.description,
    stability: form.meta.stability,
    owners: form.meta.owners,
    fields: form.fields,
    model: form.model
      ? (z.toJSONSchema(
          (form.model as AnySchemaModel).getZod()
        ) as OpenApiSchemaObject)
      : null,
    actions: form.actions,
  }));
}

/**
 * Generate TypeScript code for forms registry.
 */
export function generateFormsRegistry(
  registry: FormRegistry
): GeneratedRegistryCode {
  const forms = registry.list();
  const imports = new Set<string>();
  const registrations: string[] = [];

  for (const form of forms) {
    const formVarName =
      form.meta.key.replace(/-/g, '_') + `_v${form.meta.version}`;
    imports.add(`import { ${formVarName} } from './${form.meta.key}';`);
    registrations.push(`  .register(${formVarName})`);
  }

  const code = `/**
 * Auto-generated forms registry.
 * DO NOT EDIT - This file is generated by ContractSpec exporter.
 */
import { FormRegistry } from '@contractspec/lib.contracts';

${Array.from(imports).join('\n')}

export const formsRegistry = new FormRegistry()
${registrations.join('\n')};
`;

  return {
    code,
    fileName: 'forms-registry.ts',
  };
}
