import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const INVENTORY_START = '<!-- CONTRACT_INVENTORY:START -->';
const INVENTORY_END = '<!-- CONTRACT_INVENTORY:END -->';
const ARTIFACT_KINDS = [
	'capability',
	'feature',
	'command',
	'event',
	'query',
	'form',
	'presentation',
	'dataView',
	'docs',
	'contracts',
	'docblock',
] as const;
type ArtifactKind = (typeof ARTIFACT_KINDS)[number];
type KindOrPlain = ArtifactKind | 'plain';

type ExportEntry = {
	path: string;
	category: string;
	kind: KindOrPlain;
};

type CategoryInventory = {
	plainCount: number;
	byKind: Map<ArtifactKind, string[]>;
};

const KIND_TITLES: Record<ArtifactKind, string> = {
	capability: 'Capabilities',
	feature: 'Features',
	command: 'Commands',
	event: 'Events',
	query: 'Queries',
	form: 'Forms',
	presentation: 'Presentations',
	dataView: 'Data views',
	docs: 'Docs contracts',
	contracts: 'Contracts artifacts',
	docblock: 'DocBlocks',
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(scriptDir, '..');
const packageJsonPath = path.resolve(pkgRoot, 'package.json');
const readmePath = path.resolve(pkgRoot, 'README.md');
const typesPath = path.resolve(pkgRoot, 'src/types.ts');

const kindSet = new Set<string>(ARTIFACT_KINDS);

function readContractTypes(): string[] {
	const source = fs.readFileSync(typesPath, 'utf8');
	const block = source.match(/export type ContractSpecType\s*=([\s\S]*?);/);
	if (!block?.[1]) {
		throw new Error('Unable to locate ContractSpecType in src/types.ts');
	}
	return Array.from(block[1].matchAll(/'([^']+)'/g))
		.map((match) => match[1])
		.filter((value): value is string => Boolean(value))
		.sort((a, b) => a.localeCompare(b));
}

function readExportEntries(): ExportEntry[] {
	const packageJson = JSON.parse(fs.readFileSync(packageJsonPath, 'utf8')) as {
		exports?: Record<string, unknown>;
	};
	const exportKeys = Object.keys(packageJson.exports ?? {})
		.filter((entry) => entry !== '.')
		.sort((a, b) => a.localeCompare(b));

	return exportKeys.map((entry) => {
		const normalized = entry.replace(/^\.\//, '');
		const segments = normalized.split('/');
		const leaf = segments[segments.length - 1] ?? normalized;
		const suffix = leaf.includes('.') ? (leaf.split('.').at(-1) ?? '') : '';
		const kind = kindSet.has(suffix) ? (suffix as ArtifactKind) : 'plain';
		return {
			path: normalized,
			category: segments[0] ?? normalized,
			kind,
		};
	});
}

function buildInventory(
	entries: ExportEntry[]
): Map<string, CategoryInventory> {
	const inventory = new Map<string, CategoryInventory>();
	for (const entry of entries) {
		const current =
			inventory.get(entry.category) ??
			({
				plainCount: 0,
				byKind: new Map<ArtifactKind, string[]>(),
			} as CategoryInventory);

		if (entry.kind === 'plain') {
			current.plainCount += 1;
		} else {
			const paths = current.byKind.get(entry.kind) ?? [];
			paths.push(entry.path);
			current.byKind.set(entry.kind, paths);
		}
		inventory.set(entry.category, current);
	}

	for (const [, category] of inventory) {
		for (const [kind, paths] of category.byKind) {
			category.byKind.set(
				kind,
				[...paths].sort((a, b) => a.localeCompare(b))
			);
		}
	}
	return inventory;
}

function countKinds(entries: ExportEntry[]): Map<ArtifactKind, number> {
	const counts = new Map<ArtifactKind, number>(
		ARTIFACT_KINDS.map((kind) => [kind, 0])
	);
	for (const entry of entries) {
		if (entry.kind !== 'plain') {
			counts.set(entry.kind, (counts.get(entry.kind) ?? 0) + 1);
		}
	}
	return counts;
}

function buildMarkdown(args: {
	totalExports: number;
	contractTypes: string[];
	kindCounts: Map<ArtifactKind, number>;
	inventory: Map<string, CategoryInventory>;
}): string {
	const { totalExports, contractTypes, kindCounts, inventory } = args;
	const categories = [...inventory.keys()].sort((a, b) => a.localeCompare(b));

	const lines: string[] = [
		`The package currently exposes **${totalExports} subpath exports**. This map is auto-generated for high-context navigation and AI grounding.`,
		'',
		'> Auto-generated by `bun run readme:inventory` (`scripts/update-readme-contract-inventory.ts`). Do not edit this section manually.',
		'',
		'### 1) Registry-level contract types (semantic model)',
		'',
		'From `src/types.ts`, `ContractSpecType` currently includes:',
		'',
		...contractTypes.map((typeName) => `- \`${typeName}\``),
		'',
		'### 2) Export/file artifact kinds (suffix-based)',
		'',
		'These are the concrete contract artifact kinds visible in package exports:',
		'',
		...ARTIFACT_KINDS.map(
			(kind) => `- \`.${kind}\` (${kindCounts.get(kind) ?? 0})`
		),
		'',
		'### 3) Category -> kinds matrix',
		'',
	];

	for (const category of categories) {
		const categoryData = inventory.get(category);
		if (!categoryData) continue;
		const parts: string[] = [];
		for (const kind of ARTIFACT_KINDS) {
			const count = categoryData.byKind.get(kind)?.length ?? 0;
			if (count > 0) parts.push(`\`${kind}(${count})\``);
		}
		if (categoryData.plainCount > 0) {
			parts.push(`\`plain(${categoryData.plainCount})\``);
		}
		lines.push(`- \`${category}\`: ${parts.join(', ')}`);
	}

	lines.push('', '### 4) Fully enumerated named contracts by category', '');
	for (const category of categories) {
		const categoryData = inventory.get(category);
		if (!categoryData) continue;

		lines.push(`#### ${category}`, '');
		for (const kind of ARTIFACT_KINDS) {
			const paths = categoryData.byKind.get(kind) ?? [];
			if (paths.length === 0) continue;
			lines.push(`- ${KIND_TITLES[kind]} (${paths.length}):`);
			lines.push(...paths.map((entryPath) => `  - \`${entryPath}\``));
		}
		lines.push(
			`- Plain exports (non-suffix artifacts): \`${categoryData.plainCount}\``,
			''
		);
	}

	lines.push('### 5) DocBlock coverage map (for AI context retrieval)', '');
	lines.push(
		'`*.docblock` exports are narrative/architecture assets and are high-value context for retrieval pipelines.',
		''
	);
	for (const category of categories) {
		const count = inventory.get(category)?.byKind.get('docblock')?.length ?? 0;
		if (count > 0) {
			lines.push(`- \`${category}\`: ${count}`);
		}
	}

	return lines.join('\n');
}

function writeInventorySection(generated: string): void {
	const readme = fs.readFileSync(readmePath, 'utf8');
	const startIndex = readme.indexOf(INVENTORY_START);
	const endIndex = readme.indexOf(INVENTORY_END);
	if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) {
		throw new Error(
			`README markers ${INVENTORY_START} / ${INVENTORY_END} not found.`
		);
	}

	const before = readme.slice(0, startIndex + INVENTORY_START.length);
	const after = readme.slice(endIndex);
	const nextReadme = `${before}\n\n${generated}\n\n${after}`;
	fs.writeFileSync(
		readmePath,
		nextReadme.endsWith('\n') ? nextReadme : `${nextReadme}\n`,
		'utf8'
	);
}

export function updateReadmeInventory(): {
	exportsCount: number;
	categoryCount: number;
} {
	const entries = readExportEntries();
	const contractTypes = readContractTypes();
	const inventory = buildInventory(entries);
	const kindCounts = countKinds(entries);
	const generated = buildMarkdown({
		totalExports: entries.length,
		contractTypes,
		kindCounts,
		inventory,
	});
	writeInventorySection(generated);
	return { exportsCount: entries.length, categoryCount: inventory.size };
}
