title: "[Idea] "
labels: ["ideas"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! We love hearing how we can improve.

  - type: textarea
    id: problem
    attributes:
      label: problem related to this idea
      description: Is your idea related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: idea
    attributes:
      label: Describe your idea
      description: A clear and concise description of what you want to happen.
      placeholder: It would be great if...
    validations:
      required: true
