title: "[Q&A] "
labels: ["q-a"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to start a discussion! We'll do our best to answer your question.

  - type: textarea
    id: question
    attributes:
      label: What is your question?
      description: Please describe your question in detail.
      placeholder: I was wondering how to...
    validations:
      required: true
