import { describe, expect, test } from 'bun:test';
import {
  stripGeneratedHeader,
  packNameToIdentifier,
  extractFirstHeading,
  combineMarkdown,
  wrapSection,
} from '../../src/utils/markdown.js';

describe('stripGeneratedHeader', () => {
  test('strips generated-by comment', () => {
    const input = '<!-- Generated by agentpacks -->\n\n# Title\nContent';
    const result = stripGeneratedHeader(input);
    expect(result).not.toContain('Generated by agentpacks');
    expect(result).toContain('# Title');
  });

  test('returns content unchanged if no header', () => {
    const input = '# Title\nContent';
    expect(stripGeneratedHeader(input)).toBe(input);
  });
});

describe('packNameToIdentifier', () => {
  test('converts pack name to PascalCase', () => {
    expect(packNameToIdentifier('my-pack')).toBe('MyPack');
  });

  test('handles multi-segment names', () => {
    expect(packNameToIdentifier('my-cool-pack')).toBe('MyCoolPack');
  });

  test('handles scoped names', () => {
    const result = packNameToIdentifier('@scope/pack-name');
    expect(typeof result).toBe('string');
    expect(result.length).toBeGreaterThan(0);
  });
});

describe('extractFirstHeading', () => {
  test('extracts h1 heading', () => {
    expect(extractFirstHeading('# My Title\nContent')).toBe('My Title');
  });

  test('extracts h2 heading when no h1', () => {
    expect(extractFirstHeading('## Sub Title\nContent')).toBe('Sub Title');
  });

  test('returns null when no heading', () => {
    expect(extractFirstHeading('Just content')).toBeNull();
  });
});

describe('combineMarkdown', () => {
  test('combines sections with separator', () => {
    const result = combineMarkdown(['Section 1', 'Section 2']);
    expect(result).toContain('Section 1');
    expect(result).toContain('Section 2');
  });

  test('handles empty sections', () => {
    const result = combineMarkdown([]);
    expect(result).toBe('');
  });
});

describe('wrapSection', () => {
  test('wraps content with heading', () => {
    const result = wrapSection('Title', 'Content here');
    expect(result).toContain('# Title');
    expect(result).toContain('Content here');
  });

  test('supports custom heading level', () => {
    const result = wrapSection('Sub', 'Body', 3);
    expect(result).toContain('### Sub');
  });
});
