/**
 * Strip the generated-by header from file content.
 */
export function stripGeneratedHeader(content: string): string {
  return content
    .replace(/^<!-- Generated by agentpacks.*-->\n/, '')
    .replace(/^\/\/ Generated by agentpacks.*\n/, '');
}

/**
 * Convert a pack name to a valid identifier (PascalCase).
 */
export function packNameToIdentifier(packName: string): string {
  return packName
    .split(/[-_.]/)
    .filter((part) => part.length > 0)
    .map((part) => part.charAt(0)!.toUpperCase() + part.slice(1))
    .join('');
}

/**
 * Extract the first heading from markdown content.
 */
export function extractFirstHeading(content: string): string | null {
  const match = content.match(/^#{1,6}\s+(.+)$/m);
  return match?.[1]?.trim() ?? null;
}

/**
 * Combine multiple markdown contents with separator.
 */
export function combineMarkdown(
  sections: string[],
  separator = '\n\n---\n\n'
): string {
  return sections.filter(Boolean).join(separator);
}

/**
 * Wrap content in a markdown section with heading.
 */
export function wrapSection(
  heading: string,
  content: string,
  level = 2
): string {
  const prefix = '#'.repeat(level);
  return `${prefix} ${heading}\n\n${content}`;
}
