import type { DocBlock } from '@lssm/lib.contracts/docs';
import { registerDocBlocks } from '../registry';

export const tech_PHASE_2_AI_NATIVE_OPERATIONS_DocBlocks: DocBlock[] = [
  {
    id: 'docs.tech.PHASE_2_AI_NATIVE_OPERATIONS',
    title: 'Phase 2: AI-Native Operations',
    summary: '_Last updated: 2025-11-20_',
    kind: 'reference',
    visibility: 'public',
    route: '/docs/tech/PHASE_2_AI_NATIVE_OPERATIONS',
    tags: ['tech', 'PHASE_2_AI_NATIVE_OPERATIONS'],
    body: '# Phase 2: AI-Native Operations\n\n_Last updated: 2025-11-20_\n\nPhase 2 turns ContractSpec into an AI-first operations stack. The new libraries below are the building blocks used by support bots, growth agents, and human-in-the-loop flows.\n\n## Libraries\n\n### @lssm/lib.ai-agent\n\n- **Spec + Registry**: `defineAgent`, `AgentRegistry` keep agent definitions type-safe.\n- **Runner**: `AgentRunner` drives LLM conversations, tool calls, retries, escalation, and telemetry hooks.\n- **Tools**: `ToolExecutor` standardizes schema validation + timeouts.\n- **Memory**: `InMemoryAgentMemory` + interfaces for plugging persistent stores.\n- **Approvals**: new `ApprovalWorkflow` + `InMemoryApprovalStore` capture low-confidence decisions and surface them to reviewers.\n\n### @lssm/lib.support-bot\n\nComposable support automation primitives:\n\n- `TicketClassifier` \u2192 heuristics + optional LLM validation for category, priority, sentiment.\n- `TicketResolver` \u2192 RAG pipeline backed by knowledge spaces.\n- `AutoResponder` \u2192 tone-aware drafts with citations.\n- `SupportFeedbackLoop` \u2192 tracks resolution rates.\n- `createSupportTools` \u2192 ready-made tool definitions for AgentRunner.\n\n### @lssm/lib.content-gen\n\nContent generators that consume a `ContentBrief` and output production-ready assets:\n\n- `BlogGenerator`, `LandingPageGenerator`, `EmailCampaignGenerator`, `SocialPostGenerator`.\n- `SeoOptimizer` builds metadata + schema markup.\n\n### @lssm/lib.analytics\n\nQueryless analytics helpers:\n\n- `FunnelAnalyzer` \u2013 conversion/drop-off per step.\n- `CohortTracker` \u2013 retention + LTV per cohort.\n- `ChurnPredictor` \u2013 recency/frequency/error scoring.\n- `GrowthHypothesisGenerator` \u2013 surfaces experiment ideas from metric trends.\n\n### @lssm/lib.growth\n\nA/B testing toolkit:\n\n- `ExperimentRegistry` + `ExperimentRunner` \u2013 deterministic bucketing.\n- `ExperimentTracker` \u2013 persist exposures + metrics.\n- `StatsEngine` \u2013 Welch\u2019s t-test + improvement calculations.\n\n### Human-in-the-loop UI\n\n`@lssm/lib.design-system` now exposes:\n\n- `ApprovalQueue` \u2013 list + act on pending approvals.\n- `AgentMonitor` \u2013 live view of agent sessions with confidence + status.\n\n## Examples\n\n- `examples/ai-support-bot/setup.ts` shows ticket classification \u2192 resolution \u2192 response draft.\n- `examples/content-generation/generate.ts` produces blog, landing, email, social, SEO output from one brief.\n\n## Next Steps\n\n1. Wire these libraries into vertical apps (H-Circle, ArtisanOS, etc.).\n2. Add background workers that consume the new analytics/growth trackers.\n3. Expand web-landing to highlight these Phase 2 capabilities (see separate TODO).\n',
  },
];
registerDocBlocks(tech_PHASE_2_AI_NATIVE_OPERATIONS_DocBlocks);
