import type { BehaviorSupportDimensions } from './behavior-support';

export const BEHAVIOR_SUPPORT_PRESET_IDS = [
	'steadyMomentum',
	'activationFirst',
	'permissionFirst',
	'deepWorkBuilder',
	'recoveryFirst',
	'identityBuilder',
	'selfAuthorityBuilder',
	'socialMomentum',
	'deadlineSprint',
	'minimalNudge',
] as const;

export type BehaviorSupportPresetId =
	(typeof BEHAVIOR_SUPPORT_PRESET_IDS)[number];

export const BEHAVIOR_SUPPORT_PRESETS = {
	steadyMomentum: {
		attention: 'next-step',
		activation: 'prompted',
		actionScale: 'standard',
		rhythm: 'steady',
		environment: 'structured',
		challenge: 'moderate',
		meaningFrame: 'progress',
		permission: 'proceed',
		selfAuthority: 'structured',
		accountability: 'self-review',
		recovery: 'resume',
		reflection: 'brief',
	},
	activationFirst: {
		attention: 'next-step',
		activation: 'guided-start',
		actionScale: 'small',
		rhythm: 'flexible',
		environment: 'structured',
		challenge: 'low',
		meaningFrame: 'relief',
		permission: 'start-smaller',
		selfAuthority: 'confidence-building',
		accountability: 'private',
		recovery: 'resume',
		reflection: 'brief',
	},
	permissionFirst: {
		attention: 'ambient',
		activation: 'prompted',
		actionScale: 'small',
		rhythm: 'flexible',
		environment: 'open',
		challenge: 'low',
		meaningFrame: 'agency',
		permission: 'renegotiate',
		selfAuthority: 'confidence-building',
		accountability: 'private',
		recovery: 'renegotiate',
		reflection: 'brief',
	},
	deepWorkBuilder: {
		attention: 'priority',
		activation: 'ritual',
		actionScale: 'standard',
		rhythm: 'time-boxed',
		environment: 'focused',
		challenge: 'stretch',
		meaningFrame: 'mastery',
		permission: 'proceed',
		selfAuthority: 'high-autonomy',
		accountability: 'self-review',
		recovery: 'repair',
		reflection: 'standard',
	},
	recoveryFirst: {
		attention: 'next-step',
		activation: 'guided-start',
		actionScale: 'small',
		rhythm: 'flexible',
		environment: 'structured',
		challenge: 'low',
		meaningFrame: 'relief',
		permission: 'renegotiate',
		selfAuthority: 'confidence-building',
		accountability: 'private',
		recovery: 'repair',
		reflection: 'brief',
	},
	identityBuilder: {
		attention: 'review',
		activation: 'ritual',
		actionScale: 'standard',
		rhythm: 'steady',
		environment: 'structured',
		challenge: 'moderate',
		meaningFrame: 'agency',
		permission: 'proceed',
		selfAuthority: 'structured',
		accountability: 'self-review',
		recovery: 'repair',
		reflection: 'standard',
	},
	selfAuthorityBuilder: {
		attention: 'priority',
		activation: 'prompted',
		actionScale: 'standard',
		rhythm: 'steady',
		environment: 'structured',
		challenge: 'moderate',
		meaningFrame: 'agency',
		permission: 'proceed',
		selfAuthority: 'confidence-building',
		accountability: 'self-review',
		recovery: 'repair',
		reflection: 'standard',
	},
	socialMomentum: {
		attention: 'priority',
		activation: 'prompted',
		actionScale: 'standard',
		rhythm: 'steady',
		environment: 'collaborative',
		challenge: 'moderate',
		meaningFrame: 'belonging',
		permission: 'proceed',
		selfAuthority: 'structured',
		accountability: 'peer-review',
		recovery: 'repair',
		reflection: 'brief',
	},
	deadlineSprint: {
		attention: 'priority',
		activation: 'prompted',
		actionScale: 'small',
		rhythm: 'deadline-driven',
		environment: 'focused',
		challenge: 'stretch',
		meaningFrame: 'impact',
		permission: 'proceed',
		selfAuthority: 'structured',
		accountability: 'self-review',
		recovery: 'resume',
		reflection: 'brief',
	},
	minimalNudge: {
		attention: 'ambient',
		activation: 'self-start',
		actionScale: 'standard',
		rhythm: 'flexible',
		environment: 'open',
		challenge: 'moderate',
		meaningFrame: 'progress',
		permission: 'proceed',
		selfAuthority: 'high-autonomy',
		accountability: 'private',
		recovery: 'resume',
		reflection: 'none',
	},
} satisfies Record<BehaviorSupportPresetId, BehaviorSupportDimensions>;

export function getBehaviorSupportPresetDimensions(
	id: BehaviorSupportPresetId
): BehaviorSupportDimensions {
	return { ...BEHAVIOR_SUPPORT_PRESETS[id] };
}
