/**
 * Mock tool data for testing and demos.
 */
export const MOCK_TOOLS = [
  {
    id: 'tool-1',
    organizationId: 'demo-org',
    name: 'Web Search',
    slug: 'web-search',
    description: 'Search the web for real-time information using Brave API.',
    category: 'RETRIEVAL' as const,
    status: 'ACTIVE' as const,
    parametersSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search query' },
        numResults: { type: 'number', default: 10 },
      },
      required: ['query'],
    },
    outputSchema: { type: 'array', items: { type: 'object' } },
    implementationType: 'http' as const,
    implementationConfig: {
      url: 'https://api.brave.com/search',
      method: 'GET',
    },
    maxInvocationsPerMinute: 60,
    timeoutMs: 30000,
    version: '1.0.0',
    tags: ['search', 'web'],
    createdAt: new Date('2024-01-01T00:00:00Z'),
    updatedAt: new Date('2024-02-15T10:00:00Z'),
  },
  {
    id: 'tool-2',
    organizationId: 'demo-org',
    name: 'SQL Query',
    slug: 'sql-query',
    description: 'Execute read-only SQL queries against the data warehouse.',
    category: 'RETRIEVAL' as const,
    status: 'ACTIVE' as const,
    parametersSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'SQL query' },
        maxRows: { type: 'number', default: 100 },
      },
      required: ['query'],
    },
    outputSchema: { type: 'object' },
    implementationType: 'function' as const,
    implementationConfig: { handler: 'executeSqlQuery' },
    maxInvocationsPerMinute: 30,
    timeoutMs: 60000,
    version: '1.1.0',
    tags: ['sql', 'database'],
    createdAt: new Date('2024-01-05T00:00:00Z'),
    updatedAt: new Date('2024-03-10T14:00:00Z'),
  },
  {
    id: 'tool-3',
    organizationId: 'demo-org',
    name: 'Email Sender',
    slug: 'email-sender',
    description: 'Send emails via SMTP or API.',
    category: 'COMMUNICATION' as const,
    status: 'ACTIVE' as const,
    parametersSchema: {
      type: 'object',
      properties: {
        to: { type: 'string' },
        subject: { type: 'string' },
        body: { type: 'string' },
      },
      required: ['to', 'subject', 'body'],
    },
    implementationType: 'http' as const,
    implementationConfig: { url: '/api/send-email', method: 'POST' },
    maxInvocationsPerMinute: 10,
    timeoutMs: 30000,
    version: '1.0.0',
    tags: ['email', 'communication'],
    createdAt: new Date('2024-02-01T00:00:00Z'),
    updatedAt: new Date('2024-02-01T00:00:00Z'),
  },
  {
    id: 'tool-4',
    organizationId: 'demo-org',
    name: 'GitHub Integration',
    slug: 'github-integration',
    description: 'Interact with GitHub repositories, PRs, and issues.',
    category: 'INTEGRATION' as const,
    status: 'ACTIVE' as const,
    parametersSchema: {
      type: 'object',
      properties: {
        action: {
          type: 'string',
          enum: ['list_prs', 'get_pr', 'create_comment'],
        },
        repo: { type: 'string' },
        params: { type: 'object' },
      },
      required: ['action', 'repo'],
    },
    implementationType: 'http' as const,
    implementationConfig: { url: 'https://api.github.com', auth: 'token' },
    maxInvocationsPerMinute: 100,
    timeoutMs: 15000,
    version: '2.0.0',
    tags: ['github', 'integration', 'code'],
    createdAt: new Date('2024-02-20T00:00:00Z'),
    updatedAt: new Date('2024-04-01T09:00:00Z'),
  },
  {
    id: 'tool-5',
    organizationId: 'demo-org',
    name: 'Calculator',
    slug: 'calculator',
    description: 'Perform mathematical calculations.',
    category: 'COMPUTATION' as const,
    status: 'ACTIVE' as const,
    parametersSchema: {
      type: 'object',
      properties: {
        expression: {
          type: 'string',
          description: 'Math expression to evaluate',
        },
      },
      required: ['expression'],
    },
    outputSchema: {
      type: 'object',
      properties: { result: { type: 'number' } },
    },
    implementationType: 'function' as const,
    implementationConfig: { handler: 'evaluateMath' },
    timeoutMs: 5000,
    version: '1.0.0',
    tags: ['math', 'utility'],
    createdAt: new Date('2024-01-10T00:00:00Z'),
    updatedAt: new Date('2024-01-10T00:00:00Z'),
  },
];
