// export const metadata: Metadata = {
//   title: 'Tenant Isolation Safety | ContractSpec',
//   description: 'How to ensure data never leaks between tenants.',
// };

export default function TenantIsolationSafetyPage() {
  return (
    <div className="space-y-8">
      <div className="space-y-4">
        <h1 className="text-4xl font-bold">Tenant Isolation</h1>
        <p className="text-muted-foreground text-lg">
          Preventing cross-tenant data leaks is the #1 security priority for any
          SaaS. ContractSpec employs "Defense in Depth" to ensure safety.
        </p>
      </div>

      <div className="space-y-4">
        <h2 className="text-2xl font-bold">Layer 1: RLS Middleware</h2>
        <p>
          The primary defense is the Prisma middleware that rewrites queries to
          include <code>WHERE tenantId = ?</code>. This protects against
          developer error (forgetting to filter).
        </p>
      </div>

      <div className="space-y-4">
        <h2 className="text-2xl font-bold">Layer 2: Isolation Validator</h2>
        <p>
          For high-security environments, you can use the{' '}
          <code>IsolationValidator</code> in your test suite to verify that
          every query generated by your operations actually includes the tenant
          ID.
        </p>
        <pre className="bg-muted rounded-lg border p-4 text-sm">
          {`import { IsolationValidator } from '@contractspec/lib.multi-tenancy/isolation';

test('findUser query is isolated', () => {
  const isValid = IsolationValidator.validateQuery(
    'User',
    'findFirst',
    args,
    'tenant-123'
  );
  expect(isValid).toBe(true);
});`}
        </pre>
      </div>

      <div className="space-y-4">
        <h2 className="text-2xl font-bold">Layer 3: Policy Engine</h2>
        <p>
          The Policy Decision Point (PDP) verifies that the authenticated user
          actually belongs to the requested tenant before any operation logic
          runs.
        </p>
      </div>
    </div>
  );
}
