import { defineFeature } from './features';

export const ContractsSpecFeature = defineFeature({
	meta: {
		key: 'libs.contracts-spec',
		version: '1.0.0',
		title: 'Contracts Spec',
		description: 'Spec definitions and registries for ContractSpec',
		domain: 'contracts-spec',
		owners: ['@contractspec-core'],
		tags: ['package', 'libs', 'contracts-spec'],
		stability: 'experimental',
	},
	operations: [
		{ key: 'acp.fs.access', version: '1.0.0' },
		{ key: 'acp.prompt.turn', version: '1.0.0' },
		{ key: 'acp.session.init', version: '1.0.0' },
		{ key: 'acp.session.resume', version: '1.0.0' },
		{ key: 'acp.session.stop', version: '1.0.0' },
		{ key: 'acp.terminal.exec', version: '1.0.0' },
		{ key: 'acp.tool.calls', version: '1.0.0' },
		{ key: 'agent.approvals', version: '1.0.0' },
		{ key: 'agent.cancel', version: '1.0.0' },
		{ key: 'agent.run', version: '1.0.0' },
		{ key: 'agent.artifacts', version: '1.0.0' },
		{ key: 'agent.status', version: '1.0.0' },
		{ key: 'appConfig.updateTenantBranding', version: '1.0.0' },
		{ key: 'appConfig.verifyCustomDomain', version: '1.0.0' },
		{ key: 'appConfig.updateBlueprintTranslationCatalog', version: '1.0.0' },
		{ key: 'appConfig.updateTenantTranslations', version: '1.0.0' },
		{ key: 'appConfig.getResolvedBranding', version: '1.0.0' },
		{ key: 'appConfig.resolveMessage', version: '1.0.0' },
		{ key: 'appConfig.lifecycle.createDraft', version: '1.0.0' },
		{ key: 'appConfig.lifecycle.promoteToPreview', version: '1.0.0' },
		{ key: 'appConfig.lifecycle.publish', version: '1.0.0' },
		{ key: 'appConfig.lifecycle.rollback', version: '1.0.0' },
		{ key: 'appConfig.lifecycle.listVersions', version: '1.0.0' },
		{ key: 'appConfig.lifecycle.getVersion', version: '1.0.0' },
		{ key: 'context.pack.snapshot', version: '1.0.0' },
		{ key: 'context.pack.describe', version: '1.0.0' },
		{ key: 'context.pack.search', version: '1.0.0' },
		{ key: 'controlPlane.execution.abort', version: '1.0.0' },
		{ key: 'controlPlane.execution.approve', version: '1.0.0' },
		{ key: 'controlPlane.execution.cancel', version: '1.0.0' },
		{ key: 'controlPlane.execution.evidence.export', version: '1.0.0' },
		{ key: 'controlPlane.execution.pause', version: '1.0.0' },
		{ key: 'controlPlane.execution.reject', version: '1.0.0' },
		{ key: 'controlPlane.execution.resume', version: '1.0.0' },
		{ key: 'controlPlane.execution.retry', version: '1.0.0' },
		{ key: 'controlPlane.execution.shutdown', version: '1.0.0' },
		{ key: 'controlPlane.execution.start', version: '1.0.0' },
		{ key: 'controlPlane.intent.submit', version: '1.0.0' },
		{ key: 'controlPlane.plan.compile', version: '1.0.0' },
		{ key: 'controlPlane.plan.verify', version: '1.0.0' },
		{ key: 'controlPlane.skill.disable', version: '1.0.0' },
		{ key: 'controlPlane.skill.install', version: '1.0.0' },
		{ key: 'controlPlane.execution.get', version: '1.0.0' },
		{ key: 'controlPlane.execution.lane.get', version: '1.0.0' },
		{ key: 'controlPlane.execution.lane.list', version: '1.0.0' },
		{ key: 'controlPlane.execution.list', version: '1.0.0' },
		{ key: 'controlPlane.policy.explain', version: '1.0.0' },
		{ key: 'controlPlane.skill.list', version: '1.0.0' },
		{ key: 'controlPlane.skill.verify', version: '1.0.0' },
		{ key: 'controlPlane.trace.get', version: '1.0.0' },
		{ key: 'database.dictionary.get', version: '1.0.0' },
		{ key: 'database.migrations.list', version: '1.0.0' },
		{ key: 'database.query.readonly', version: '1.0.0' },
		{ key: 'database.schema.describe', version: '1.0.0' },
		{ key: 'docs.generate', version: '1.0.0' },
		{ key: 'docs.publish', version: '1.0.0' },
		{ key: 'AddNumbersSpec', version: '1.0.0' },
		{ key: 'docs.contract.reference', version: '1.0.0' },
		{ key: 'docs_search', version: '1.0.0' },
		{ key: 'harness.evaluation.run', version: '1.0.0' },
		{ key: 'harness.run.cancel', version: '1.0.0' },
		{ key: 'harness.run.start', version: '1.0.0' },
		{ key: 'harness.evaluation.get', version: '1.0.0' },
		{ key: 'harness.evidence.get', version: '1.0.0' },
		{ key: 'harness.evidence.list', version: '1.0.0' },
		{ key: 'harness.run.get', version: '1.0.0' },
		{ key: 'harness.target.resolve', version: '1.0.0' },
		{ key: 'knowledge.source.create', version: '1.0.0' },
		{ key: 'knowledge.source.update', version: '1.0.0' },
		{ key: 'knowledge.source.delete', version: '1.0.0' },
		{ key: 'knowledge.source.list', version: '1.0.0' },
		{ key: 'knowledge.source.triggerSync', version: '1.0.0' },
		{ key: 'base.onboarding.saveDraft', version: '1.0.0' },
		{ key: 'base.onboarding.getDraft', version: '1.0.0' },
		{ key: 'base.onboarding.deleteDraft', version: '1.0.0' },
		{ key: 'base.onboarding.complete', version: '1.0.0' },
		{ key: 'report.getContractVerificationStatus', version: '1.0.0' },
		{ key: 'provider-ranking.benchmark.ingest', version: '1.0.0' },
		{ key: 'provider-ranking.benchmark.run-custom', version: '1.0.0' },
		{ key: 'provider-ranking.ranking.refresh', version: '1.0.0' },
		{ key: 'provider-ranking.benchmark.results.list', version: '1.0.0' },
		{ key: 'provider-ranking.model.profile.get', version: '1.0.0' },
		{ key: 'provider-ranking.ranking.get', version: '1.0.0' },
	],
	events: [
		{ key: 'agent.approval.requested', version: '1.0.0' },
		{ key: 'agent.run.completed', version: '1.0.0' },
		{ key: 'agent.run.failed', version: '1.0.0' },
		{ key: 'agent.run.started', version: '1.0.0' },
		{ key: 'app_config.draft_created', version: '1.0.0' },
		{ key: 'app_config.promoted_to_preview', version: '1.0.0' },
		{ key: 'app_config.published', version: '1.0.0' },
		{ key: 'app_config.rolled_back', version: '1.0.0' },
		{ key: 'context.snapshot.created', version: '1.0.0' },
		{ key: 'controlPlane.execution.completed', version: '1.0.0' },
		{ key: 'controlPlane.execution.failed', version: '1.0.0' },
		{ key: 'controlPlane.execution.step.blocked', version: '1.0.0' },
		{ key: 'controlPlane.execution.step.completed', version: '1.0.0' },
		{ key: 'controlPlane.execution.step.started', version: '1.0.0' },
		{ key: 'controlPlane.intent.received', version: '1.0.0' },
		{ key: 'controlPlane.plan.compiled', version: '1.0.0' },
		{ key: 'controlPlane.plan.rejected', version: '1.0.0' },
		{ key: 'controlPlane.skill.installed', version: '1.0.0' },
		{ key: 'controlPlane.skill.rejected', version: '1.0.0' },
		{ key: 'docs.generated', version: '1.0.0' },
		{ key: 'docs.published', version: '1.0.0' },
		{ key: 'harness.evaluation.completed', version: '1.0.0' },
		{ key: 'harness.evidence.captured', version: '1.0.0' },
		{ key: 'harness.run.completed', version: '1.0.0' },
		{ key: 'harness.run.failed', version: '1.0.0' },
		{ key: 'harness.run.started', version: '1.0.0' },
		{ key: 'harness.step.blocked', version: '1.0.0' },
		{ key: 'harness.step.completed', version: '1.0.0' },
		{ key: 'harness.step.started', version: '1.0.0' },
		{ key: 'provider-ranking.benchmark.custom.completed', version: '1.0.0' },
		{ key: 'provider-ranking.benchmark.ingested', version: '1.0.0' },
		{ key: 'provider-ranking.ranking.updated', version: '1.0.0' },
	],
	presentations: [
		{ key: 'agent.run.audit', version: '1.0.0' },
		{ key: 'context.snapshot.summary', version: '1.0.0' },
		{ key: 'docs.layout', version: '1.0.0' },
		{ key: 'docs.reference.page', version: '1.0.0' },
		{ key: 'harness.run.audit', version: '1.0.0' },
		{ key: 'provider-ranking.model.comparison', version: '1.0.0' },
	],
	dataViews: [
		{ key: 'agent.run.index', version: '1.0.0' },
		{ key: 'context.snapshot.index', version: '1.0.0' },
		{ key: 'report.contractVerificationTable', version: '1.0.0' },
		{ key: 'database.schema.index', version: '1.0.0' },
		{ key: 'docs.contract.reference.view', version: '1.0.0' },
		{ key: 'docs.index.view', version: '1.0.0' },
		{ key: 'docs.examples.catalog.view', version: '1.0.0' },
		{ key: 'harness.evaluation.index', version: '1.0.0' },
		{ key: 'harness.evidence.index', version: '1.0.0' },
		{ key: 'harness.run.index', version: '1.0.0' },
		{ key: 'provider-ranking.benchmark.results.index', version: '1.0.0' },
		{ key: 'provider-ranking.ranking.index', version: '1.0.0' },
	],
});
