import {
	type DocBlock,
	type DocBlockManifestEntry,
	packageDocBlocks,
} from '@contractspec/lib.contracts-spec/docs';
import {
	buildPackageDocManifest,
	convertSpecToDocBlock,
	extractModuleDocData,
	loadSpecFromSource,
	type SpecScanResult,
	scanAllSpecsFromSource,
	scanSpecSource,
} from '@contractspec/module.workspace';
import path from 'path';
import type { WorkspaceAdapters } from '../../ports/logger';
import { ModuleResolver } from '../modules/module-resolver';

export interface DocsServiceOptions {
	outputDir?: string;
	format?: 'markdown' | 'html' | 'json';
	rootPath?: string;
}

export interface DocsServiceResult {
	blocks: DocBlock[];
	count: number;
}

interface AuthoredSourceDocEntry {
	entry: DocBlockManifestEntry;
	filePath: string;
}

/**
 * Generate documentation from spec files.
 */
export async function generateDocsFromSpecs(
	specFiles: string[],
	options: DocsServiceOptions,
	adapters: WorkspaceAdapters
): Promise<DocsServiceResult> {
	const { fs, logger } = adapters;
	const blocks: DocBlock[] = [];

	logger.info(`Generating docs for ${specFiles.length} files...`);

	if (options.outputDir) {
		await fs.mkdir(options.outputDir);
	}

	// Initialize ModuleResolver
	const resolver = new ModuleResolver(adapters);
	// 1. Scan all specs to build the module index
	const scanResults: SpecScanResult[] = [];
	for (const file of specFiles) {
		try {
			const content = await fs.readFile(file);
			const results = scanAllSpecsFromSource(content, file);
			if (results.length > 0) {
				scanResults.push(...results);
			} else {
				// Fallback if no multi-specs found, try single scan logic
				const single = scanSpecSource(content, file);
				if (single.specType !== 'unknown') {
					scanResults.push(single);
				}
			}
		} catch (_err) {
			// ignore read errors
		}
	}

	resolver.initialize(scanResults);
	const authoredEntries = await loadAuthoredDocEntriesFromSourceFiles(
		specFiles,
		adapters
	);

	for (const authoredEntry of authoredEntries) {
		blocks.push(authoredEntry.entry.block);
		logger.debug(`Loaded authored doc ${authoredEntry.entry.id}`);

		if (options.outputDir) {
			await writeDocBlockFile(
				authoredEntry.entry.block,
				authoredEntry.filePath,
				options.outputDir,
				resolver,
				fs
			);
		}
	}

	for (const file of specFiles) {
		try {
			const parsedList = await loadSpecFromSource(file);

			if (!parsedList?.length) {
				logger.warn(`Could not parse spec from ${file}`);
				continue;
			}

			for (const parsed of parsedList) {
				const block = convertSpecToDocBlock(parsed, {
					rootPath: options.rootPath,
				});
				blocks.push(block);
				logger.debug(`Generated doc for ${block.id}`);

				if (!options.outputDir) {
					continue;
				}

				await writeDocBlockFile(block, file, options.outputDir, resolver, fs);
			}
		} catch (error) {
			logger.error(
				`Error processing ${file}: ${error instanceof Error ? error.message : String(error)}`
			);
		}
	}

	if (options.outputDir) {
		logger.info(`Wrote ${blocks.length} doc files to ${options.outputDir}`);
	}

	return { blocks, count: blocks.length };
}

export async function loadAuthoredDocBlocksFromSourceFiles(
	sourceFiles: string[],
	adapters: Pick<WorkspaceAdapters, 'fs'>
): Promise<DocBlock[]> {
	const entries = await loadAuthoredDocEntriesFromSourceFiles(
		sourceFiles,
		adapters
	);
	return entries.map(({ entry }) => entry.block);
}

export function loadPackageAuthoredDocBlocks(
	packageName: string,
	srcRoot: string
): DocBlock[] {
	return packageDocBlocks(buildPackageDocManifest({ packageName, srcRoot }));
}

async function loadAuthoredDocEntriesFromSourceFiles(
	sourceFiles: string[],
	adapters: Pick<WorkspaceAdapters, 'fs'>
): Promise<AuthoredSourceDocEntry[]> {
	const uniqueFiles = [...new Set(sourceFiles)].sort((left, right) =>
		left.localeCompare(right)
	);
	const entries: AuthoredSourceDocEntry[] = [];

	for (const filePath of uniqueFiles) {
		const sourceText = await adapters.fs.readFile(filePath);
		const sourceModule = filePath
			.replace(/\\/g, '/')
			.replace(/\.[cm]?[jt]sx?$/, '');
		const moduleData = extractModuleDocData(sourceText, filePath, sourceModule);

		for (const entry of moduleData.entries) {
			entries.push({ entry, filePath });
		}
	}

	return entries;
}

async function writeDocBlockFile(
	block: DocBlock,
	file: string,
	outputDir: string,
	resolver: ModuleResolver,
	fs: WorkspaceAdapters['fs']
): Promise<void> {
	const moduleDef = resolver.resolve(file);
	const targetDir = moduleDef
		? path.join(outputDir, moduleDef.key)
		: path.join(outputDir, '_common');

	await fs.mkdir(targetDir);

	const filePath = path.join(targetDir, `${block.id}.md`);
	const generatedContent = `<!-- @generated - This file was generated by ContractSpec. Do not edit manually. -->\n\n${block.body}`;
	await fs.writeFile(filePath, generatedContent);
}
