import {
  type DocBlock,
  defaultDocRegistry,
} from '@contractspec/lib.contracts/docs';
import {
  loadSpecFromSource,
  convertSpecToDocBlock,
} from '@contractspec/module.workspace';
import type { WorkspaceAdapters } from '../../ports/logger';

export interface DocsServiceOptions {
  outputDir?: string;
  format?: 'markdown' | 'html' | 'json';
  rootPath?: string;
}

export interface DocsServiceResult {
  blocks: DocBlock[];
  count: number;
}

/**
 * Generate documentation from spec files.
 */
export async function generateDocsFromSpecs(
  specFiles: string[],
  options: DocsServiceOptions,
  adapters: WorkspaceAdapters
): Promise<DocsServiceResult> {
  const { fs, logger } = adapters;
  const blocks: DocBlock[] = [];

  logger.info(`Generating docs for ${specFiles.length} files...`);

  if (options.outputDir) {
    await fs.mkdir(options.outputDir);
  }

  const root = options.rootPath ?? fs.resolve('.');

  for (const file of specFiles) {
    try {
      const parsedList = await loadSpecFromSource(file);

      if (parsedList && parsedList.length > 0) {
        for (const parsed of parsedList) {
          const block = convertSpecToDocBlock(parsed, {
            rootPath: options.rootPath,
          });
          // Register globally? Or locally?
          // DocRegistry instance
          defaultDocRegistry.register(block);
          blocks.push(block);
          logger.debug(`Generated doc for ${block.id}`);

          if (options.outputDir) {
            // Respect boundaries: use source file structure
            const relPath = fs.relative(root, file);
            const subDir = fs.dirname(relPath);
            const targetDir = fs.join(options.outputDir, subDir);

            // Ensure subdirectory exists
            await fs.mkdir(targetDir);

            const filename = `${block.id}.md`; // Or sanitize
            const path = fs.join(targetDir, filename);
            const generatedContent = `<!-- @generated - This file was generated by ContractSpec. Do not edit manually. -->\n\n${block.body}`;
            await fs.writeFile(path, generatedContent);
          }
        }
      } else {
        logger.warn(`Could not parse spec from ${file}`);
      }
    } catch (error) {
      logger.error(
        `Error processing ${file}: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  }

  if (options.outputDir) {
    logger.info(`Wrote ${blocks.length} doc files to ${options.outputDir}`);
  }

  return { blocks, count: blocks.length };
}
