/**
 * Mock data for agent-console handlers
 */

// ============ Agent Mock Data ============

export const MOCK_AGENTS = [
  {
    id: 'agent-1',
    organizationId: 'demo-org',
    name: 'Customer Support Bot',
    slug: 'customer-support-bot',
    description: 'Handles tier-1 customer inquiries and routes complex issues.',
    status: 'ACTIVE' as const,
    modelProvider: 'OPENAI' as const,
    modelName: 'gpt-4o-mini',
    modelConfig: { temperature: 0.7 },
    systemPrompt: 'You are a helpful customer support assistant.',
    toolChoice: 'auto' as const,
    maxIterations: 10,
    timeoutMs: 120000,
    version: '1.0.0',
    tags: ['support', 'tier-1'],
    createdAt: new Date('2024-01-15T10:00:00Z'),
    updatedAt: new Date('2024-03-20T14:30:00Z'),
  },
  {
    id: 'agent-2',
    organizationId: 'demo-org',
    name: 'Code Review Assistant',
    slug: 'code-review-assistant',
    description: 'Reviews pull requests and provides actionable feedback.',
    status: 'ACTIVE' as const,
    modelProvider: 'ANTHROPIC' as const,
    modelName: 'claude-sonnet-4-20250514',
    modelConfig: { temperature: 0.3 },
    systemPrompt: 'You are a code review expert.',
    toolChoice: 'auto' as const,
    maxIterations: 15,
    timeoutMs: 180000,
    version: '2.1.0',
    tags: ['code', 'review', 'dev'],
    createdAt: new Date('2024-02-10T09:00:00Z'),
    updatedAt: new Date('2024-04-05T11:15:00Z'),
  },
  {
    id: 'agent-3',
    organizationId: 'demo-org',
    name: 'Data Analyst',
    slug: 'data-analyst',
    description: 'Queries databases and generates insights from data.',
    status: 'PAUSED' as const,
    modelProvider: 'OPENAI' as const,
    modelName: 'gpt-4o',
    modelConfig: { temperature: 0.5 },
    systemPrompt: 'You are a data analyst expert in SQL and analytics.',
    toolChoice: 'required' as const,
    maxIterations: 20,
    timeoutMs: 300000,
    version: '1.2.0',
    tags: ['data', 'analytics', 'sql'],
    createdAt: new Date('2024-03-01T08:00:00Z'),
    updatedAt: new Date('2024-04-10T16:45:00Z'),
  },
  {
    id: 'agent-4',
    organizationId: 'demo-org',
    name: 'Meeting Scheduler',
    slug: 'meeting-scheduler',
    description: 'Schedules meetings and manages calendar conflicts.',
    status: 'DRAFT' as const,
    modelProvider: 'GOOGLE' as const,
    modelName: 'gemini-2.0-flash',
    modelConfig: { temperature: 0.2 },
    systemPrompt: 'You help schedule and organize meetings efficiently.',
    toolChoice: 'auto' as const,
    maxIterations: 5,
    timeoutMs: 60000,
    version: '0.1.0',
    tags: ['calendar', 'scheduling'],
    createdAt: new Date('2024-04-01T12:00:00Z'),
    updatedAt: new Date('2024-04-01T12:00:00Z'),
  },
];

// ============ Tool Mock Data ============

export const MOCK_TOOLS = [
  {
    id: 'tool-1',
    organizationId: 'demo-org',
    name: 'Web Search',
    slug: 'web-search',
    description: 'Search the web for real-time information using Brave API.',
    category: 'RETRIEVAL' as const,
    status: 'ACTIVE' as const,
    parametersSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search query' },
        numResults: { type: 'number', default: 10 },
      },
      required: ['query'],
    },
    outputSchema: { type: 'array', items: { type: 'object' } },
    implementationType: 'http' as const,
    implementationConfig: { url: 'https://api.brave.com/search', method: 'GET' },
    maxInvocationsPerMinute: 60,
    timeoutMs: 30000,
    version: '1.0.0',
    tags: ['search', 'web'],
    createdAt: new Date('2024-01-01T00:00:00Z'),
    updatedAt: new Date('2024-02-15T10:00:00Z'),
  },
  {
    id: 'tool-2',
    organizationId: 'demo-org',
    name: 'SQL Query',
    slug: 'sql-query',
    description: 'Execute read-only SQL queries against the data warehouse.',
    category: 'RETRIEVAL' as const,
    status: 'ACTIVE' as const,
    parametersSchema: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'SQL query' },
        maxRows: { type: 'number', default: 100 },
      },
      required: ['query'],
    },
    outputSchema: { type: 'object' },
    implementationType: 'function' as const,
    implementationConfig: { handler: 'executeSqlQuery' },
    maxInvocationsPerMinute: 30,
    timeoutMs: 60000,
    version: '1.1.0',
    tags: ['sql', 'database'],
    createdAt: new Date('2024-01-05T00:00:00Z'),
    updatedAt: new Date('2024-03-10T14:00:00Z'),
  },
  {
    id: 'tool-3',
    organizationId: 'demo-org',
    name: 'Email Sender',
    slug: 'email-sender',
    description: 'Send emails via SMTP or API.',
    category: 'COMMUNICATION' as const,
    status: 'ACTIVE' as const,
    parametersSchema: {
      type: 'object',
      properties: {
        to: { type: 'string' },
        subject: { type: 'string' },
        body: { type: 'string' },
      },
      required: ['to', 'subject', 'body'],
    },
    implementationType: 'http' as const,
    implementationConfig: { url: '/api/send-email', method: 'POST' },
    maxInvocationsPerMinute: 10,
    timeoutMs: 30000,
    version: '1.0.0',
    tags: ['email', 'communication'],
    createdAt: new Date('2024-02-01T00:00:00Z'),
    updatedAt: new Date('2024-02-01T00:00:00Z'),
  },
  {
    id: 'tool-4',
    organizationId: 'demo-org',
    name: 'GitHub Integration',
    slug: 'github-integration',
    description: 'Interact with GitHub repositories, PRs, and issues.',
    category: 'INTEGRATION' as const,
    status: 'ACTIVE' as const,
    parametersSchema: {
      type: 'object',
      properties: {
        action: { type: 'string', enum: ['list_prs', 'get_pr', 'create_comment'] },
        repo: { type: 'string' },
        params: { type: 'object' },
      },
      required: ['action', 'repo'],
    },
    implementationType: 'http' as const,
    implementationConfig: { url: 'https://api.github.com', auth: 'token' },
    maxInvocationsPerMinute: 100,
    timeoutMs: 15000,
    version: '2.0.0',
    tags: ['github', 'integration', 'code'],
    createdAt: new Date('2024-02-20T00:00:00Z'),
    updatedAt: new Date('2024-04-01T09:00:00Z'),
  },
  {
    id: 'tool-5',
    organizationId: 'demo-org',
    name: 'Calculator',
    slug: 'calculator',
    description: 'Perform mathematical calculations.',
    category: 'COMPUTATION' as const,
    status: 'ACTIVE' as const,
    parametersSchema: {
      type: 'object',
      properties: {
        expression: { type: 'string', description: 'Math expression to evaluate' },
      },
      required: ['expression'],
    },
    outputSchema: { type: 'object', properties: { result: { type: 'number' } } },
    implementationType: 'function' as const,
    implementationConfig: { handler: 'evaluateMath' },
    timeoutMs: 5000,
    version: '1.0.0',
    tags: ['math', 'utility'],
    createdAt: new Date('2024-01-10T00:00:00Z'),
    updatedAt: new Date('2024-01-10T00:00:00Z'),
  },
];

// ============ Run Mock Data ============

export const MOCK_RUNS = [
  {
    id: 'run-1',
    organizationId: 'demo-org',
    agentId: 'agent-1',
    agentName: 'Customer Support Bot',
    userId: 'user-1',
    sessionId: 'session-1',
    input: { message: 'How do I reset my password?', context: {} },
    output: { response: 'You can reset your password by clicking...' },
    status: 'COMPLETED' as const,
    totalTokens: 1250,
    promptTokens: 800,
    completionTokens: 450,
    totalIterations: 3,
    durationMs: 4500,
    estimatedCostUsd: 0.0025,
    queuedAt: new Date('2024-04-15T10:00:00Z'),
    startedAt: new Date('2024-04-15T10:00:01Z'),
    completedAt: new Date('2024-04-15T10:00:05Z'),
  },
  {
    id: 'run-2',
    organizationId: 'demo-org',
    agentId: 'agent-2',
    agentName: 'Code Review Assistant',
    userId: 'user-2',
    input: { message: 'Review PR #123', context: { prNumber: 123 } },
    status: 'IN_PROGRESS' as const,
    totalTokens: 3500,
    promptTokens: 3000,
    completionTokens: 500,
    totalIterations: 5,
    queuedAt: new Date('2024-04-15T10:30:00Z'),
    startedAt: new Date('2024-04-15T10:30:02Z'),
  },
  {
    id: 'run-3',
    organizationId: 'demo-org',
    agentId: 'agent-1',
    agentName: 'Customer Support Bot',
    userId: 'user-1',
    input: { message: 'What are your business hours?' },
    output: { response: 'Our business hours are 9 AM to 5 PM EST...' },
    status: 'COMPLETED' as const,
    totalTokens: 800,
    promptTokens: 500,
    completionTokens: 300,
    totalIterations: 2,
    durationMs: 2100,
    estimatedCostUsd: 0.0012,
    queuedAt: new Date('2024-04-15T09:00:00Z'),
    startedAt: new Date('2024-04-15T09:00:01Z'),
    completedAt: new Date('2024-04-15T09:00:03Z'),
  },
  {
    id: 'run-4',
    organizationId: 'demo-org',
    agentId: 'agent-3',
    agentName: 'Data Analyst',
    userId: 'user-3',
    input: { message: 'Generate sales report for Q1' },
    status: 'FAILED' as const,
    errorMessage: 'Database connection timeout',
    errorCode: 'DB_TIMEOUT',
    totalTokens: 2000,
    promptTokens: 1500,
    completionTokens: 500,
    totalIterations: 8,
    durationMs: 45000,
    queuedAt: new Date('2024-04-14T15:00:00Z'),
    startedAt: new Date('2024-04-14T15:00:05Z'),
    completedAt: new Date('2024-04-14T15:00:50Z'),
  },
  {
    id: 'run-5',
    organizationId: 'demo-org',
    agentId: 'agent-2',
    agentName: 'Code Review Assistant',
    userId: 'user-2',
    input: { message: 'Review PR #120' },
    output: { response: 'Code review complete. 3 suggestions...' },
    status: 'COMPLETED' as const,
    totalTokens: 5200,
    promptTokens: 4000,
    completionTokens: 1200,
    totalIterations: 7,
    durationMs: 15000,
    estimatedCostUsd: 0.0156,
    queuedAt: new Date('2024-04-14T11:00:00Z'),
    startedAt: new Date('2024-04-14T11:00:03Z'),
    completedAt: new Date('2024-04-14T11:00:18Z'),
  },
];

// ============ Run Steps Mock Data ============

export const MOCK_RUN_STEPS = [
  {
    id: 'step-1',
    runId: 'run-1',
    stepNumber: 1,
    type: 'MESSAGE_CREATION' as const,
    input: { message: 'How do I reset my password?' },
    output: { parsed: true },
    status: 'COMPLETED' as const,
    tokensUsed: 200,
    durationMs: 500,
    startedAt: new Date('2024-04-15T10:00:01Z'),
    completedAt: new Date('2024-04-15T10:00:01Z'),
  },
  {
    id: 'step-2',
    runId: 'run-1',
    stepNumber: 2,
    type: 'TOOL_CALL' as const,
    toolId: 'tool-1',
    toolName: 'Web Search',
    input: { query: 'password reset documentation' },
    output: { results: [] },
    status: 'COMPLETED' as const,
    tokensUsed: 500,
    durationMs: 2000,
    startedAt: new Date('2024-04-15T10:00:02Z'),
    completedAt: new Date('2024-04-15T10:00:04Z'),
  },
  {
    id: 'step-3',
    runId: 'run-1',
    stepNumber: 3,
    type: 'MESSAGE_CREATION' as const,
    output: { response: 'You can reset your password by clicking...' },
    status: 'COMPLETED' as const,
    tokensUsed: 550,
    durationMs: 2000,
    startedAt: new Date('2024-04-15T10:00:04Z'),
    completedAt: new Date('2024-04-15T10:00:05Z'),
  },
];

// ============ Run Logs Mock Data ============

export const MOCK_RUN_LOGS = [
  {
    id: 'log-1',
    runId: 'run-1',
    stepId: 'step-1',
    level: 'INFO' as const,
    message: 'Run started',
    timestamp: new Date('2024-04-15T10:00:01Z'),
    source: 'orchestrator',
  },
  {
    id: 'log-2',
    runId: 'run-1',
    stepId: 'step-2',
    level: 'DEBUG' as const,
    message: 'Calling tool: Web Search',
    data: { toolId: 'tool-1' },
    timestamp: new Date('2024-04-15T10:00:02Z'),
    source: 'tool-executor',
  },
  {
    id: 'log-3',
    runId: 'run-1',
    stepId: 'step-2',
    level: 'INFO' as const,
    message: 'Tool execution completed',
    data: { duration: 2000 },
    timestamp: new Date('2024-04-15T10:00:04Z'),
    source: 'tool-executor',
  },
  {
    id: 'log-4',
    runId: 'run-1',
    level: 'INFO' as const,
    message: 'Run completed successfully',
    timestamp: new Date('2024-04-15T10:00:05Z'),
    source: 'orchestrator',
  },
];

