// This file is automatically generated by i18next-cli. Do not edit manually.
import { resources } from '../i18n';

declare module 'i18next' {
  interface CustomTypeOptions {
    enableSelector: true;
    defaultNS: 'common';
    resources: (typeof resources)['fr'];
  }
}
