name: 'ContractSpec Drift'
description: 'Detect ContractSpec drift on main or scheduled runs'
author: 'LSSM'
branding:
  icon: 'alert-triangle'
  color: 'blue'

inputs:
  package-manager:
    description: 'Package manager to use (bun|npm|pnpm|yarn)'
    required: false
    default: 'bun'
  working-directory:
    description: 'Working directory for running commands'
    required: false
    default: '.'
  generate-command:
    description: 'Command to regenerate artifacts'
    required: true
  on-drift:
    description: 'Behavior when drift is detected (fail|issue|pr)'
    required: false
    default: 'fail'
  drift-paths-allowlist:
    description: 'Comma-separated glob patterns to check for drift'
    required: false
    default: ''
  token:
    description: 'GitHub token for issues/PRs'
    required: false
    default: '${{ github.token }}'

outputs:
  drift-detected:
    description: 'Whether drift was detected'
    value: ${{ steps.result.outputs.drift_detected }}

runs:
  using: 'composite'
  steps:
    - name: Set action defaults
      shell: bash
      run: |
        echo "PACKAGE_MANAGER=${{ inputs.package-manager }}" >> $GITHUB_ENV
        echo "WORKING_DIRECTORY=${{ inputs.working-directory }}" >> $GITHUB_ENV
        echo "GENERATE_COMMAND=${{ inputs.generate-command }}" >> $GITHUB_ENV
        echo "ON_DRIFT=${{ inputs.on-drift }}" >> $GITHUB_ENV
        echo "DRIFT_ALLOWLIST=${{ inputs.drift-paths-allowlist }}" >> $GITHUB_ENV
        echo "COMMENT_TOKEN=${{ inputs.token }}" >> $GITHUB_ENV
        echo "TURBO_TELEMETRY_DISABLED=1" >> $GITHUB_ENV
        echo "DO_NOT_TRACK=1" >> $GITHUB_ENV

    - name: Setup Bun
      if: env.PACKAGE_MANAGER == 'bun'
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: '1.3.8'

    - name: Setup Node
      if: env.PACKAGE_MANAGER != 'bun'
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      shell: bash
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        case "$PACKAGE_MANAGER" in
          bun)
            if [ -f "bun.lock" ] || [ -f "bun.lockb" ]; then
              bun install --frozen-lockfile
            else
              bun install
            fi
            ;;
          npm)
            if [ -f "package-lock.json" ]; then
              npm ci
            else
              npm install
            fi
            ;;
          pnpm)
            corepack enable
            pnpm install --frozen-lockfile
            ;;
          yarn)
            corepack enable
            yarn install --frozen-lockfile
            ;;
        esac

    - name: Build local ContractSpec CLI (if present)
      if: env.PACKAGE_MANAGER == 'bun'
      shell: bash
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        if [ -f "packages/apps/cli-contractspec/package.json" ]; then
          bun run build --filter=@contractspec/app.cli-contractspec
        fi

    - name: Run generate command
      shell: bash
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        if [ -z "$GENERATE_COMMAND" ]; then
          echo "::error::generate-command is required for drift checks"
          exit 1
        fi
        bash -lc "$GENERATE_COMMAND"

    - name: Check drift
      shell: bash
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        mkdir -p .contractspec-ci
        git status --porcelain > .contractspec-ci/drift-status.txt
        python - <<'PY'
        import json
        import os
        from pathlib import Path

        contracts_data = []
        contracts_path = Path(".contractspec-ci/contracts.json")
        report_data = {}

        # Load contracts data if available
        if contracts_path.exists():
          try:
            contracts_result = json.loads(contracts_path.read_text())
            contracts_data = contracts_result.get("contracts", [])
          except json.JSONDecodeError:
            pass

        # Load existing report if exists
        report_data_path = Path(".contractspec-ci/report-data.json")
        if report_data_path.exists():
          try:
            report_data = json.loads(report_data_path.read_text())
          except json.JSONDecodeError:
            pass

        # Update report data with contracts
        report_data["contracts"] = contracts_data

        report_data["whatChanged"] = {
          "summary": "Drift check completed.",
          "detailsPath": "",
        }
        report_data["risk"] = {
          "status": "unknown",
          "breaking": 0,
          "nonBreaking": 0,
        }
        report_data["validation"] = {
          "status": "skipped",
          "outputPath": "",
        }
        report_data["drift"] = {
          "status": os.environ.get("DRIFT_STATUS", "skipped"),
          "files": Path(".contractspec-ci/drift-files.txt").read_text().splitlines()
          if Path(".contractspec-ci/drift-files.txt").exists()
          else [],
        }
        report_data["nextSteps"] = []

        if report_data["drift"]["status"] == "fail":
          report_data["nextSteps"].append("Run the generate command locally and commit drift fixes.")

        Path(".contractspec-ci/report-data.json").write_text(json.dumps(report_data, indent=2))
        PY

        if [ -s ".contractspec-ci/drift-files.txt" ]; then
          echo "DRIFT_STATUS=fail" >> $GITHUB_ENV
          echo "DRIFT_DETECTED=true" >> $GITHUB_ENV
        else
          echo "DRIFT_STATUS=pass" >> $GITHUB_ENV
          echo "DRIFT_DETECTED=false" >> $GITHUB_ENV
        fi

    - name: Build report data
      shell: bash
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        # Collect contract verification status
        echo "Collecting contract verification status..."
        node "${{ github.action_path }}/operation-executor.js" "report.getContractVerificationStatus" "1.0.0" '{"projectPath": "'"$(pwd)"'"}' > .contractspec-ci/contracts.json || echo "[]" > .contractspec-ci/contracts.json

        # Load contracts data and existing report data

        # Load contracts data if available
        contracts_data = []
        contracts_path = Path(".contractspec-ci/contracts.json")
        if contracts_path.exists():
          try:
            contracts_result = json.loads(contracts_path.read_text())
            contracts_data = contracts_result.get("contracts", [])
          except json.JSONDecodeError:
            pass

        report = {
          "whatChanged": {
            "summary": "Drift check completed.",
            "detailsPath": "",
          },
          "risk": {
            "status": "unknown",
            "breaking": 0,
            "nonBreaking": 0,
          },
          "validation": {
            "status": "skipped",
            "outputPath": "",
          },
          "drift": {
            "status": os.environ.get("DRIFT_STATUS", "skipped"),
            "files": Path(".contractspec-ci/drift-files.txt").read_text().splitlines()
            if Path(".contractspec-ci/drift-files.txt").exists()
            else [],
          },
          "contracts": contracts_data,
          "nextSteps": [],
        }

        if report["drift"]["status"] == "fail":
          report["nextSteps"].append("Run the generate command locally and commit drift fixes.")

        Path(".contractspec-ci/report-data.json").write_text(json.dumps(report, indent=2))
        PY

    - name: Generate report
      shell: bash
      working-directory: ${{ env.WORKING_DIRECTORY }}
      run: |
        node "${{ github.action_path }}/dist/report.js" --data .contractspec-ci/report-data.json --output .contractspec-ci/report.md

    - name: Create issue
      if: env.DRIFT_DETECTED == 'true' && env.ON_DRIFT == 'issue'
      uses: actions/github-script@v7
      with:
        github-token: ${{ env.COMMENT_TOKEN }}
        script: |
          const fs = require("fs");
          const body = fs.readFileSync(
            `${process.env.WORKING_DIRECTORY}/.contractspec-ci/report.md`,
            "utf8",
          );
          const title = "ContractSpec drift detected";

          const { data: issues } = await github.rest.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            state: "open",
          });

          const existing = issues.find((issue) => issue.title === title);
          if (existing) {
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: existing.number,
              body,
            });
          } else {
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
            });
          }

    - name: Create drift PR
      if: env.DRIFT_DETECTED == 'true' && env.ON_DRIFT == 'pr'
      shell: bash
      working-directory: ${{ env.WORKING_DIRECTORY }}
      env:
        GH_TOKEN: ${{ env.COMMENT_TOKEN }}
      run: |
        BRANCH="contractspec/drift-$(date +%Y%m%d%H%M%S)"
        git checkout -b "$BRANCH"
        git add -A
        git commit -m "chore(contractspec): fix drift"
        git push origin "$BRANCH"
        gh pr create \
          --title "chore(contractspec): fix drift" \
          --body-file .contractspec-ci/report.md \
          --base "${{ github.event.repository.default_branch }}" \
          --head "$BRANCH"

    - name: Finalize results
      id: result
      shell: bash
      run: |
        DRIFT_DETECTED="${DRIFT_DETECTED:-false}"
        echo "drift_detected=$DRIFT_DETECTED" >> $GITHUB_OUTPUT

        if [ "$DRIFT_DETECTED" = "true" ] && [ "$ON_DRIFT" = "fail" ]; then
          echo "::error::ContractSpec drift detected."
          exit 1
        fi
