// Generated by scripts/generate-example-registry.ts. Do not edit manually.

export interface GeneratedInlineExamplePreviewRegistration {
  key: string;
  exportName: string;
  loadModule: () => Promise<Record<string, unknown>>;
}

export const INLINE_EXAMPLE_PREVIEW_REGISTRY: readonly GeneratedInlineExamplePreviewRegistration[] = [
  {
    key: "agent-console",
    exportName: "ExecutionConsoleHost",
    loadModule: () => import("@contractspec/example.agent-console/ui"),
  },
  {
    key: "ai-chat-assistant",
    exportName: "AiChatAssistantDashboard",
    loadModule: () => import("@contractspec/example.ai-chat-assistant/ui"),
  },
  {
    key: "analytics-dashboard",
    exportName: "AnalyticsDashboard",
    loadModule: () => import("@contractspec/example.analytics-dashboard/ui"),
  },
  {
    key: "crm-pipeline",
    exportName: "CrmDashboard",
    loadModule: () => import("@contractspec/example.crm-pipeline/ui"),
  },
  {
    key: "data-grid-showcase",
    exportName: "DataGridShowcase",
    loadModule: () => import("@contractspec/example.data-grid-showcase/ui"),
  },
  {
    key: "in-app-docs",
    exportName: "InAppDocsViewer",
    loadModule: () => import("@contractspec/example.in-app-docs/ui"),
  },
  {
    key: "integration-hub",
    exportName: "IntegrationDashboard",
    loadModule: () => import("@contractspec/example.integration-hub/ui"),
  },
  {
    key: "learning-journey-registry",
    exportName: "LearningMiniApp",
    loadModule: () => import("@contractspec/example.learning-journey-registry/ui"),
  },
  {
    key: "marketplace",
    exportName: "MarketplaceDashboard",
    loadModule: () => import("@contractspec/example.marketplace/ui"),
  },
  {
    key: "policy-safe-knowledge-assistant",
    exportName: "PolicySafeKnowledgeAssistantDashboard",
    loadModule: () => import("@contractspec/example.policy-safe-knowledge-assistant/ui"),
  },
  {
    key: "saas-boilerplate",
    exportName: "SaasDashboard",
    loadModule: () => import("@contractspec/example.saas-boilerplate/ui"),
  },
  {
    key: "visualization-showcase",
    exportName: "VisualizationShowcase",
    loadModule: () => import("@contractspec/example.visualization-showcase/ui"),
  },
  {
    key: "workflow-system",
    exportName: "WorkflowDashboard",
    loadModule: () => import("@contractspec/example.workflow-system/ui"),
  },
];
