name: Validate App Blueprints

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate-blueprints:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.3

      - name: Install dependencies
        run: bun install
#        run: bun install --frozen-lockfile

      - name: Validate example blueprints and tenant configs
        run: bun run validate:blueprints
