// Generated by scripts/generate-example-registry.ts. Do not edit manually.
import type { ExampleSpec } from '@contractspec/lib.contracts-spec/examples/types';
import type { ExampleSource } from './registry';

export const EXAMPLE_REGISTRY = [
	{
		meta: {
			key: 'agent-console',
			version: '1.0.0',
			title: 'Agent Console',
			description:
				'Agent Console example - AI agent orchestration with tools, runs, and logs',
			kind: 'template',
			visibility: 'public',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'agent-console', 'agents', 'autonomous'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.agent-console',
		},
	},
	{
		meta: {
			key: 'ai-chat-assistant',
			version: '1.0.0',
			title: 'Ai Chat Assistant',
			description:
				'Focused AI chat assistant template with MCP tools, reasoning, chain of thought, sources, and suggestions.',
			kind: 'template',
			visibility: 'public',
			stability: 'beta',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'ai-chat-assistant'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.ai-chat-assistant',
		},
	},
	{
		meta: {
			key: 'examples.ai-support-bot',
			version: '1.0.0',
			title: 'Ai Support Bot',
			description:
				'AI support bot example: classify and resolve a support ticket using @contractspec/lib.support-bot.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'ai-support-bot'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.ai-support-bot',
		},
	},
	{
		meta: {
			key: 'analytics-dashboard',
			version: '1.0.0',
			title: 'Analytics Dashboard',
			description:
				'Analytics Dashboard example with widgets and query engine for ContractSpec',
			kind: 'template',
			visibility: 'public',
			stability: 'stable',
			owners: ['@contractspec-core'],
			tags: [
				'package',
				'examples',
				'analytics-dashboard',
				'analytics',
				'dashboard',
			],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.analytics-dashboard',
		},
	},
	{
		meta: {
			key: 'calendar-google',
			version: '1.0.0',
			title: 'Calendar Google',
			description:
				'Google Calendar integration example: list and create events.',
			kind: 'template',
			visibility: 'public',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'calendar-google'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.calendar-google',
		},
	},
	{
		meta: {
			key: 'examples.content-generation',
			version: '1.0.0',
			title: 'Content Generation',
			description:
				'Content generation example using @contractspec/lib.content-gen.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'content-generation'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.content-generation',
		},
	},
	{
		meta: {
			key: 'examples.crm-pipeline',
			version: '1.0.0',
			title: 'Crm Pipeline',
			description: 'CRM Pipeline - Contacts, Companies, Deals, Tasks',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'crm-pipeline'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.crm-pipeline',
		},
	},
	{
		meta: {
			key: 'data-grid-showcase',
			version: '1.0.0',
			title: 'Data Grid Showcase',
			description:
				'Focused data-grid example for ContractSpec table capabilities',
			kind: 'ui',
			visibility: 'public',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'data-grid-showcase'],
		},
		surfaces: {
			templates: false,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.data-grid-showcase',
		},
	},
	{
		meta: {
			key: 'examples.email-gmail',
			version: '1.0.0',
			title: 'Email Gmail',
			description:
				'Gmail integration example: inbound threads and outbound messages.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'email-gmail'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.email-gmail',
		},
	},
	{
		meta: {
			key: 'form-showcase',
			version: '1.0.0',
			title: 'Form Showcase',
			description:
				'Focused ContractSpec form template covering field kinds, conditional rules, and layout flows.',
			summary:
				'Use this template when you want only form contracts: all core fields, responsive layouts, steps, sections, arrays, and validation hints.',
			kind: 'template',
			visibility: 'public',
			stability: 'stable',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'form-showcase', 'forms', 'template', 'ui'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.form-showcase',
			docs: './docs',
		},
	},
	{
		meta: {
			key: 'examples.harness-lab',
			version: '1.0.0',
			title: 'Harness Lab',
			description:
				'Focused harness example for ContractSpec scenarios, suites, orchestration, and runtime adapters.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'harness-lab'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.harness-lab',
		},
	},
	{
		meta: {
			key: 'examples.in-app-docs',
			version: '1.0.0',
			title: 'In App Docs',
			description:
				'Example showing how to use DocBlock for in-app documentation for non-technical users',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'in-app-docs'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.in-app-docs',
		},
	},
	{
		meta: {
			key: 'examples.integration-hub',
			version: '1.0.0',
			title: 'Integration Hub',
			description:
				'Integration Hub example with sync engine and field mappings for ContractSpec',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'integration-hub'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.integration-hub',
		},
	},
	{
		meta: {
			key: 'examples.integration-posthog',
			version: '1.0.0',
			title: 'Integration Posthog',
			description:
				'PostHog analytics integration example: capture events, run HogQL, and manage feature flags.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'integration-posthog'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.integration-posthog',
		},
	},
	{
		meta: {
			key: 'examples.integration-stripe',
			version: '1.0.0',
			title: 'Integration Stripe',
			description:
				'Integration example – Stripe Payments (blueprint + workflow + tenant config).',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'integration-stripe'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.integration-stripe',
		},
	},
	{
		meta: {
			key: 'examples.integration-supabase',
			version: '1.0.0',
			title: 'Integration Supabase',
			description:
				'Integration example - Supabase vector store + Postgres database wiring.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'integration-supabase'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.integration-supabase',
		},
	},
	{
		meta: {
			key: 'examples.kb-update-pipeline',
			version: '1.0.0',
			title: 'Kb Update Pipeline',
			description:
				'Example: KB update automation pipeline with HITL review and auditability.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'kb-update-pipeline'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.kb-update-pipeline',
		},
	},
	{
		meta: {
			key: 'examples.knowledge-canon',
			version: '1.0.0',
			title: 'Knowledge Canon',
			description:
				'Knowledge example – Product Canon space (blueprint + tenant config + source sample + runtime helper).',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'knowledge-canon'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.knowledge-canon',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-ambient-coach',
			version: '1.0.0',
			title: 'Learning Journey Ambient Coach',
			description:
				'Ambient coach learning journey example with contextual tips and follow-up actions.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-ambient-coach'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-ambient-coach',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-crm-onboarding',
			version: '1.0.0',
			title: 'Learning Journey Crm Onboarding',
			description:
				'Learning journey track that onboards users to the CRM pipeline example.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-crm-onboarding'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-crm-onboarding',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-duo-drills',
			version: '1.0.0',
			title: 'Learning Journey Duo Drills',
			description:
				'Drill-based learning journey example with SRS, XP, and streak hooks.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-duo-drills'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-duo-drills',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-platform-tour',
			version: '1.0.0',
			title: 'Learning Journey Platform Tour',
			description:
				'Learning journey track covering ContractSpec platform primitives.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-platform-tour'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-platform-tour',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-quest-challenges',
			version: '1.0.0',
			title: 'Learning Journey Quest Challenges',
			description: 'Time-bound quest/challenge learning journey example.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-quest-challenges'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-quest-challenges',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-registry',
			version: '1.0.0',
			title: 'Learning Journey Registry',
			description: 'Registry that aggregates learning journey example tracks.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-registry'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-registry',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-studio-onboarding',
			version: '1.0.0',
			title: 'Learning Journey Studio Onboarding',
			description:
				'Learning journey track for first 30 minutes in ContractSpec Studio.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-studio-onboarding'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-studio-onboarding',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-ui-coaching',
			version: '1.0.0',
			title: 'Learning Journey Ui Coaching',
			description:
				'Contextual coaching UI with tip cards and engagement tracking.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-ui-coaching'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-ui-coaching',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-ui-gamified',
			version: '1.0.0',
			title: 'Learning Journey Ui Gamified',
			description: 'Duolingo-style gamified learning UI for drills and quests.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-ui-gamified'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-ui-gamified',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-ui-onboarding',
			version: '1.0.0',
			title: 'Learning Journey Ui Onboarding',
			description: 'Developer onboarding UI with checklists and journey maps.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-ui-onboarding'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-ui-onboarding',
		},
	},
	{
		meta: {
			key: 'examples.learning-journey-ui-shared',
			version: '1.0.0',
			title: 'Learning Journey Ui Shared',
			description:
				'Shared UI components and hooks for learning journey mini-apps.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-journey-ui-shared'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-journey-ui-shared',
		},
	},
	{
		meta: {
			key: 'examples.learning-patterns',
			version: '1.0.0',
			title: 'Learning Patterns',
			description:
				'Example: drills + ambient coach + quests learning patterns, powered by Learning Journey (event-driven, deterministic).',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'learning-patterns'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.learning-patterns',
		},
	},
	{
		meta: {
			key: 'examples.lifecycle-cli',
			version: '1.0.0',
			title: 'Lifecycle Cli',
			description:
				'Lifecycle CLI demo (example): run lifecycle assessment without an HTTP server.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'lifecycle-cli'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.lifecycle-cli',
		},
	},
	{
		meta: {
			key: 'examples.lifecycle-dashboard',
			version: '1.0.0',
			title: 'Lifecycle Dashboard',
			description:
				'Lifecycle dashboard example (snippet): how to call lifecycle-managed APIs and render a status card.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'lifecycle-dashboard'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.lifecycle-dashboard',
		},
	},
	{
		meta: {
			key: 'examples.locale-jurisdiction-gate',
			version: '1.0.0',
			title: 'Locale Jurisdiction Gate',
			description:
				'Example: enforce locale + jurisdiction + kbSnapshotId + allowed scope for assistant calls (fail-closed).',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'locale-jurisdiction-gate'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.locale-jurisdiction-gate',
		},
	},
	{
		meta: {
			key: 'examples.marketplace',
			version: '1.0.0',
			title: 'Marketplace',
			description:
				'Marketplace example with orders, payouts, and reviews for ContractSpec',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'marketplace'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.marketplace',
		},
	},
	{
		meta: {
			key: 'examples.meeting-recorder-providers',
			version: '1.0.0',
			title: 'Meeting Recorder Providers',
			description:
				'Meeting recorder provider example: list meetings, transcripts, and webhooks.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'meeting-recorder-providers'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.meeting-recorder-providers',
		},
	},
	{
		meta: {
			key: 'messaging-agent-actions',
			version: '1.0.0',
			title: 'Messaging Agent Actions',
			description:
				'Safe messaging agent actions example with fixed intents, allowlisted actions, workflow dispatch, and deterministic replies.',
			kind: 'template',
			visibility: 'public',
			stability: 'beta',
			owners: ['@contractspec-core'],
			tags: [
				'package',
				'examples',
				'messaging-agent-actions',
				'agents',
				'telegram',
			],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.messaging-agent-actions',
		},
	},
	{
		meta: {
			key: 'minimal',
			version: '1.0.0',
			title: 'Minimal',
			description:
				'ContractSpec package declaration for @contractspec/example.minimal.',
			kind: 'template',
			visibility: 'public',
			stability: 'stable',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'minimal', 'quickstart'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.minimal',
		},
	},
	{
		meta: {
			key: 'examples.openbanking-powens',
			version: '1.0.0',
			title: 'Openbanking Powens',
			description:
				'OpenBanking Powens example: OAuth callback + webhook handler patterns (provider + workflows).',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'openbanking-powens'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.openbanking-powens',
		},
	},
	{
		meta: {
			key: 'opencode-cli',
			version: '1.0.0',
			title: 'Opencode Cli',
			description:
				'ContractSpec package declaration for @contractspec/example.opencode-cli.',
			kind: 'template',
			visibility: 'public',
			stability: 'stable',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'opencode-cli'],
		},
		surfaces: {
			templates: false,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.opencode-cli',
		},
	},
	{
		meta: {
			key: 'examples.personalization',
			version: '1.0.0',
			title: 'Personalization',
			description:
				'Personalization examples: behavior tracking, overlay customization, workflow extension.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'personalization'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.personalization',
		},
	},
	{
		meta: {
			key: 'examples.pocket-family-office',
			version: '1.0.0',
			title: 'Pocket Family Office',
			description:
				'Pocket Family Office example - personal finance automation with open banking',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'pocket-family-office'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.pocket-family-office',
		},
	},
	{
		meta: {
			key: 'policy-safe-knowledge-assistant',
			version: '1.0.0',
			title: 'Policy Safe Knowledge Assistant',
			description:
				'All-in-one template example: policy-safe knowledge assistant with locale/jurisdiction gating, versioned KB snapshots, HITL update pipeline, and learning hub.',
			kind: 'template',
			visibility: 'public',
			stability: 'beta',
			owners: ['@contractspec-core'],
			tags: [
				'package',
				'examples',
				'policy-safe-knowledge-assistant',
				'knowledge',
				'policy',
				'assistant',
			],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.policy-safe-knowledge-assistant',
		},
	},
	{
		meta: {
			key: 'examples.product-intent',
			version: '1.0.0',
			title: 'Product Intent',
			description:
				'Product intent example: evidence ingestion and prompt-ready outputs.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'product-intent'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.product-intent',
		},
	},
	{
		meta: {
			key: 'examples.project-management-sync',
			version: '1.0.0',
			title: 'Project Management Sync',
			description:
				'Project management sync example: Linear, Jira, and Notion work item creation.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'project-management-sync'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.project-management-sync',
		},
	},
	{
		meta: {
			key: 'examples.saas-boilerplate',
			version: '1.0.0',
			title: 'Saas Boilerplate',
			description:
				'SaaS Boilerplate - Users, Orgs, Projects, Billing, Settings',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'saas-boilerplate'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.saas-boilerplate',
		},
	},
	{
		meta: {
			key: 'examples.service-business-os',
			version: '1.0.0',
			title: 'Service Business Os',
			description:
				'Service Business OS example (clients, quotes, jobs, invoices) for ContractSpec',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'service-business-os'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.service-business-os',
		},
	},
	{
		meta: {
			key: 'examples.team-hub',
			version: '1.0.0',
			title: 'Team Hub',
			description:
				'Team Hub example with spaces, tasks, rituals, and announcements',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'team-hub'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.team-hub',
		},
	},
	{
		meta: {
			key: 'examples.versioned-knowledge-base',
			version: '1.0.0',
			title: 'Versioned Knowledge Base',
			description:
				'Example: curated, versioned knowledge base with immutable sources, rule versions, and published snapshots.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'versioned-knowledge-base'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.versioned-knowledge-base',
		},
	},
	{
		meta: {
			key: 'examples.video-api-showcase',
			version: '1.0.0',
			title: 'Video Api Showcase',
			description:
				'Generate API documentation videos from contract spec definitions using the ApiOverview composition.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'video-api-showcase'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.video-api-showcase',
		},
	},
	{
		meta: {
			key: 'examples.video-docs-terminal',
			version: '1.0.0',
			title: 'Video Docs Terminal',
			description:
				'Generate terminal demo videos from CLI walkthroughs using the TerminalDemo composition and ScriptGenerator.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'video-docs-terminal'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.video-docs-terminal',
		},
	},
	{
		meta: {
			key: 'examples.video-marketing-clip',
			version: '1.0.0',
			title: 'Video Marketing Clip',
			description:
				'Generate short-form marketing videos from content briefs using the video-gen pipeline.',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'video-marketing-clip'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.video-marketing-clip',
		},
	},
	{
		meta: {
			key: 'visualization-showcase',
			version: '1.0.0',
			title: 'Visualization Showcase',
			description:
				'Focused visualization showcase for ContractSpec primitives and design-system wrappers',
			kind: 'template',
			visibility: 'public',
			stability: 'stable',
			owners: ['@contractspec-core'],
			tags: [
				'package',
				'examples',
				'visualization-showcase',
				'visualization',
				'charts',
			],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.visualization-showcase',
		},
	},
	{
		meta: {
			key: 'voice-providers',
			version: '1.0.0',
			title: 'Voice Providers',
			description:
				'Voice provider example: Gradium and Fal text-to-speech integration patterns.',
			kind: 'template',
			visibility: 'public',
			stability: 'beta',
			owners: ['@contractspec-core'],
			tags: [
				'package',
				'examples',
				'voice-providers',
				'voice',
				'gradium',
				'fal',
			],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.voice-providers',
		},
	},
	{
		meta: {
			key: 'examples.wealth-snapshot',
			version: '1.0.0',
			title: 'Wealth Snapshot',
			description:
				'Wealth Snapshot mini-app for accounts, assets, liabilities, and goals',
			kind: 'template',
			visibility: 'experimental',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'wealth-snapshot'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.wealth-snapshot',
		},
	},
	{
		meta: {
			key: 'workflow-system',
			version: '1.0.0',
			title: 'Workflow System',
			description:
				'Workflow and approval system example for ContractSpec - State machine with role-based transitions',
			kind: 'template',
			visibility: 'public',
			stability: 'experimental',
			owners: ['@contractspec-core'],
			tags: ['package', 'examples', 'workflow-system'],
		},
		surfaces: {
			templates: true,
			sandbox: {
				enabled: true,
				modes: ['playground', 'specs'],
			},
			studio: {
				enabled: false,
				installable: false,
			},
			mcp: {
				enabled: false,
			},
		},
		entrypoints: {
			packageName: '@contractspec/example.workflow-system',
		},
	},
] satisfies readonly ExampleSpec[];

export const EXAMPLE_SOURCE_REGISTRY = [
	{
		key: 'agent-console',
		packageName: '@contractspec/example.agent-console',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/agent-console',
		defaultRef: 'main',
	},
	{
		key: 'ai-chat-assistant',
		packageName: '@contractspec/example.ai-chat-assistant',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/ai-chat-assistant',
		defaultRef: 'main',
	},
	{
		key: 'ai-support-bot',
		packageName: '@contractspec/example.ai-support-bot',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/ai-support-bot',
		defaultRef: 'main',
	},
	{
		key: 'analytics-dashboard',
		packageName: '@contractspec/example.analytics-dashboard',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/analytics-dashboard',
		defaultRef: 'main',
	},
	{
		key: 'calendar-google',
		packageName: '@contractspec/example.calendar-google',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/calendar-google',
		defaultRef: 'main',
	},
	{
		key: 'content-generation',
		packageName: '@contractspec/example.content-generation',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/content-generation',
		defaultRef: 'main',
	},
	{
		key: 'crm-pipeline',
		packageName: '@contractspec/example.crm-pipeline',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/crm-pipeline',
		defaultRef: 'main',
	},
	{
		key: 'data-grid-showcase',
		packageName: '@contractspec/example.data-grid-showcase',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/data-grid-showcase',
		defaultRef: 'main',
	},
	{
		key: 'email-gmail',
		packageName: '@contractspec/example.email-gmail',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/email-gmail',
		defaultRef: 'main',
	},
	{
		key: 'form-showcase',
		packageName: '@contractspec/example.form-showcase',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/form-showcase',
		defaultRef: 'main',
	},
	{
		key: 'harness-lab',
		packageName: '@contractspec/example.harness-lab',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/harness-lab',
		defaultRef: 'main',
	},
	{
		key: 'in-app-docs',
		packageName: '@contractspec/example.in-app-docs',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/in-app-docs',
		defaultRef: 'main',
	},
	{
		key: 'integration-hub',
		packageName: '@contractspec/example.integration-hub',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/integration-hub',
		defaultRef: 'main',
	},
	{
		key: 'integration-posthog',
		packageName: '@contractspec/example.integration-posthog',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/integration-posthog',
		defaultRef: 'main',
	},
	{
		key: 'integration-stripe',
		packageName: '@contractspec/example.integration-stripe',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/integration-stripe',
		defaultRef: 'main',
	},
	{
		key: 'integration-supabase',
		packageName: '@contractspec/example.integration-supabase',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/integration-supabase',
		defaultRef: 'main',
	},
	{
		key: 'kb-update-pipeline',
		packageName: '@contractspec/example.kb-update-pipeline',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/kb-update-pipeline',
		defaultRef: 'main',
	},
	{
		key: 'knowledge-canon',
		packageName: '@contractspec/example.knowledge-canon',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/knowledge-canon',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-ambient-coach',
		packageName: '@contractspec/example.learning-journey-ambient-coach',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-ambient-coach',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-crm-onboarding',
		packageName: '@contractspec/example.learning-journey-crm-onboarding',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-crm-onboarding',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-duo-drills',
		packageName: '@contractspec/example.learning-journey-duo-drills',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-duo-drills',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-platform-tour',
		packageName: '@contractspec/example.learning-journey-platform-tour',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-platform-tour',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-quest-challenges',
		packageName: '@contractspec/example.learning-journey-quest-challenges',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-quest-challenges',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-registry',
		packageName: '@contractspec/example.learning-journey-registry',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-registry',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-studio-onboarding',
		packageName: '@contractspec/example.learning-journey-studio-onboarding',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-studio-onboarding',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-ui-coaching',
		packageName: '@contractspec/example.learning-journey-ui-coaching',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-ui-coaching',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-ui-gamified',
		packageName: '@contractspec/example.learning-journey-ui-gamified',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-ui-gamified',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-ui-onboarding',
		packageName: '@contractspec/example.learning-journey-ui-onboarding',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-ui-onboarding',
		defaultRef: 'main',
	},
	{
		key: 'learning-journey-ui-shared',
		packageName: '@contractspec/example.learning-journey-ui-shared',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-journey-ui-shared',
		defaultRef: 'main',
	},
	{
		key: 'learning-patterns',
		packageName: '@contractspec/example.learning-patterns',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/learning-patterns',
		defaultRef: 'main',
	},
	{
		key: 'lifecycle-cli',
		packageName: '@contractspec/example.lifecycle-cli',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/lifecycle-cli',
		defaultRef: 'main',
	},
	{
		key: 'lifecycle-dashboard',
		packageName: '@contractspec/example.lifecycle-dashboard',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/lifecycle-dashboard',
		defaultRef: 'main',
	},
	{
		key: 'locale-jurisdiction-gate',
		packageName: '@contractspec/example.locale-jurisdiction-gate',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/locale-jurisdiction-gate',
		defaultRef: 'main',
	},
	{
		key: 'marketplace',
		packageName: '@contractspec/example.marketplace',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/marketplace',
		defaultRef: 'main',
	},
	{
		key: 'meeting-recorder-providers',
		packageName: '@contractspec/example.meeting-recorder-providers',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/meeting-recorder-providers',
		defaultRef: 'main',
	},
	{
		key: 'messaging-agent-actions',
		packageName: '@contractspec/example.messaging-agent-actions',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/messaging-agent-actions',
		defaultRef: 'main',
	},
	{
		key: 'minimal',
		packageName: '@contractspec/example.minimal',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/minimal',
		defaultRef: 'main',
	},
	{
		key: 'openbanking-powens',
		packageName: '@contractspec/example.openbanking-powens',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/openbanking-powens',
		defaultRef: 'main',
	},
	{
		key: 'opencode-cli',
		packageName: '@contractspec/example.opencode-cli',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/opencode-cli',
		defaultRef: 'main',
	},
	{
		key: 'personalization',
		packageName: '@contractspec/example.personalization',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/personalization',
		defaultRef: 'main',
	},
	{
		key: 'pocket-family-office',
		packageName: '@contractspec/example.pocket-family-office',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/pocket-family-office',
		defaultRef: 'main',
	},
	{
		key: 'policy-safe-knowledge-assistant',
		packageName: '@contractspec/example.policy-safe-knowledge-assistant',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/policy-safe-knowledge-assistant',
		defaultRef: 'main',
	},
	{
		key: 'product-intent',
		packageName: '@contractspec/example.product-intent',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/product-intent',
		defaultRef: 'main',
	},
	{
		key: 'project-management-sync',
		packageName: '@contractspec/example.project-management-sync',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/project-management-sync',
		defaultRef: 'main',
	},
	{
		key: 'saas-boilerplate',
		packageName: '@contractspec/example.saas-boilerplate',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/saas-boilerplate',
		defaultRef: 'main',
	},
	{
		key: 'service-business-os',
		packageName: '@contractspec/example.service-business-os',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/service-business-os',
		defaultRef: 'main',
	},
	{
		key: 'team-hub',
		packageName: '@contractspec/example.team-hub',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/team-hub',
		defaultRef: 'main',
	},
	{
		key: 'versioned-knowledge-base',
		packageName: '@contractspec/example.versioned-knowledge-base',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/versioned-knowledge-base',
		defaultRef: 'main',
	},
	{
		key: 'video-api-showcase',
		packageName: '@contractspec/example.video-api-showcase',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/video-api-showcase',
		defaultRef: 'main',
	},
	{
		key: 'video-docs-terminal',
		packageName: '@contractspec/example.video-docs-terminal',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/video-docs-terminal',
		defaultRef: 'main',
	},
	{
		key: 'video-marketing-clip',
		packageName: '@contractspec/example.video-marketing-clip',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/video-marketing-clip',
		defaultRef: 'main',
	},
	{
		key: 'visualization-showcase',
		packageName: '@contractspec/example.visualization-showcase',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/visualization-showcase',
		defaultRef: 'main',
	},
	{
		key: 'voice-providers',
		packageName: '@contractspec/example.voice-providers',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/voice-providers',
		defaultRef: 'main',
	},
	{
		key: 'wealth-snapshot',
		packageName: '@contractspec/example.wealth-snapshot',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/wealth-snapshot',
		defaultRef: 'main',
	},
	{
		key: 'workflow-system',
		packageName: '@contractspec/example.workflow-system',
		repositoryUrl: 'https://github.com/lssm-tech/contractspec.git',
		directory: 'packages/examples/workflow-system',
		defaultRef: 'main',
	},
] satisfies readonly ExampleSource[];
