// Generated by scripts/generate-example-registry.ts. Do not edit manually.
import AgentConsole from "@contractspec/example.agent-console/example";
import AiChatAssistant from "@contractspec/example.ai-chat-assistant/example";
import AiSupportBot from "@contractspec/example.ai-support-bot/example";
import AnalyticsDashboard from "@contractspec/example.analytics-dashboard/example";
import CalendarGoogle from "@contractspec/example.calendar-google/example";
import ContentGeneration from "@contractspec/example.content-generation/example";
import CrmPipeline from "@contractspec/example.crm-pipeline/example";
import DataGridShowcase from "@contractspec/example.data-grid-showcase/example";
import EmailGmail from "@contractspec/example.email-gmail/example";
import HarnessLab from "@contractspec/example.harness-lab/example";
import InAppDocs from "@contractspec/example.in-app-docs/example";
import IntegrationHub from "@contractspec/example.integration-hub/example";
import IntegrationPosthog from "@contractspec/example.integration-posthog/example";
import IntegrationStripe from "@contractspec/example.integration-stripe/example";
import IntegrationSupabase from "@contractspec/example.integration-supabase/example";
import KbUpdatePipeline from "@contractspec/example.kb-update-pipeline/example";
import KnowledgeCanon from "@contractspec/example.knowledge-canon/example";
import LearningJourneyAmbientCoach from "@contractspec/example.learning-journey-ambient-coach/example";
import LearningJourneyCrmOnboarding from "@contractspec/example.learning-journey-crm-onboarding/example";
import LearningJourneyDuoDrills from "@contractspec/example.learning-journey-duo-drills/example";
import LearningJourneyPlatformTour from "@contractspec/example.learning-journey-platform-tour/example";
import LearningJourneyQuestChallenges from "@contractspec/example.learning-journey-quest-challenges/example";
import LearningJourneyRegistry from "@contractspec/example.learning-journey-registry/example";
import LearningJourneyStudioOnboarding from "@contractspec/example.learning-journey-studio-onboarding/example";
import LearningJourneyUiCoaching from "@contractspec/example.learning-journey-ui-coaching/example";
import LearningJourneyUiGamified from "@contractspec/example.learning-journey-ui-gamified/example";
import LearningJourneyUiOnboarding from "@contractspec/example.learning-journey-ui-onboarding/example";
import LearningJourneyUiShared from "@contractspec/example.learning-journey-ui-shared/example";
import LearningPatterns from "@contractspec/example.learning-patterns/example";
import LifecycleCli from "@contractspec/example.lifecycle-cli/example";
import LifecycleDashboard from "@contractspec/example.lifecycle-dashboard/example";
import LocaleJurisdictionGate from "@contractspec/example.locale-jurisdiction-gate/example";
import Marketplace from "@contractspec/example.marketplace/example";
import MeetingRecorderProviders from "@contractspec/example.meeting-recorder-providers/example";
import MessagingAgentActions from "@contractspec/example.messaging-agent-actions/example";
import Minimal from "@contractspec/example.minimal/example";
import OpenbankingPowens from "@contractspec/example.openbanking-powens/example";
import OpencodeCli from "@contractspec/example.opencode-cli/example";
import Personalization from "@contractspec/example.personalization/example";
import PocketFamilyOffice from "@contractspec/example.pocket-family-office/example";
import PolicySafeKnowledgeAssistant from "@contractspec/example.policy-safe-knowledge-assistant/example";
import ProductIntent from "@contractspec/example.product-intent/example";
import ProjectManagementSync from "@contractspec/example.project-management-sync/example";
import SaasBoilerplate from "@contractspec/example.saas-boilerplate/example";
import ServiceBusinessOs from "@contractspec/example.service-business-os/example";
import TeamHub from "@contractspec/example.team-hub/example";
import VersionedKnowledgeBase from "@contractspec/example.versioned-knowledge-base/example";
import VideoApiShowcase from "@contractspec/example.video-api-showcase/example";
import VideoDocsTerminal from "@contractspec/example.video-docs-terminal/example";
import VideoMarketingClip from "@contractspec/example.video-marketing-clip/example";
import VisualizationShowcase from "@contractspec/example.visualization-showcase/example";
import VoiceProviders from "@contractspec/example.voice-providers/example";
import WealthSnapshot from "@contractspec/example.wealth-snapshot/example";
import WorkflowSystem from "@contractspec/example.workflow-system/example";
import type { ExampleSpec } from "@contractspec/lib.contracts-spec/examples/types";

export const EXAMPLE_REGISTRY: readonly ExampleSpec[] = [
  AgentConsole,
  AiChatAssistant,
  AiSupportBot,
  AnalyticsDashboard,
  CalendarGoogle,
  ContentGeneration,
  CrmPipeline,
  DataGridShowcase,
  EmailGmail,
  HarnessLab,
  InAppDocs,
  IntegrationHub,
  IntegrationPosthog,
  IntegrationStripe,
  IntegrationSupabase,
  KbUpdatePipeline,
  KnowledgeCanon,
  LearningJourneyAmbientCoach,
  LearningJourneyCrmOnboarding,
  LearningJourneyDuoDrills,
  LearningJourneyPlatformTour,
  LearningJourneyQuestChallenges,
  LearningJourneyRegistry,
  LearningJourneyStudioOnboarding,
  LearningJourneyUiCoaching,
  LearningJourneyUiGamified,
  LearningJourneyUiOnboarding,
  LearningJourneyUiShared,
  LearningPatterns,
  LifecycleCli,
  LifecycleDashboard,
  LocaleJurisdictionGate,
  Marketplace,
  MeetingRecorderProviders,
  MessagingAgentActions,
  Minimal,
  OpenbankingPowens,
  OpencodeCli,
  Personalization,
  PocketFamilyOffice,
  PolicySafeKnowledgeAssistant,
  ProductIntent,
  ProjectManagementSync,
  SaasBoilerplate,
  ServiceBusinessOs,
  TeamHub,
  VersionedKnowledgeBase,
  VideoApiShowcase,
  VideoDocsTerminal,
  VideoMarketingClip,
  VisualizationShowcase,
  VoiceProviders,
  WealthSnapshot,
  WorkflowSystem,
];
