import type { ExampleSpec } from '@contractspec/lib.contracts-spec/examples/types';

// Generated by scripts/generate-example-registry.ts. Do not edit manually.
import AgentConsole from '../../../examples/agent-console/src/example';
import AiChatAssistant from '../../../examples/ai-chat-assistant/src/example';
import AiSupportBot from '../../../examples/ai-support-bot/src/example';
import AnalyticsDashboard from '../../../examples/analytics-dashboard/src/example';
import CalendarGoogle from '../../../examples/calendar-google/src/example';
import ContentGeneration from '../../../examples/content-generation/src/example';
import CrmPipeline from '../../../examples/crm-pipeline/src/example';
import DataGridShowcase from '../../../examples/data-grid-showcase/src/example';
import EmailGmail from '../../../examples/email-gmail/src/example';
import InAppDocs from '../../../examples/in-app-docs/src/example';
import IntegrationHub from '../../../examples/integration-hub/src/example';
import IntegrationPosthog from '../../../examples/integration-posthog/src/example';
import IntegrationStripe from '../../../examples/integration-stripe/src/example';
import IntegrationSupabase from '../../../examples/integration-supabase/src/example';
import KbUpdatePipeline from '../../../examples/kb-update-pipeline/src/example';
import KnowledgeCanon from '../../../examples/knowledge-canon/src/example';
import LearningJourneyAmbientCoach from '../../../examples/learning-journey-ambient-coach/src/example';
import LearningJourneyCrmOnboarding from '../../../examples/learning-journey-crm-onboarding/src/example';
import LearningJourneyDuoDrills from '../../../examples/learning-journey-duo-drills/src/example';
import LearningJourneyPlatformTour from '../../../examples/learning-journey-platform-tour/src/example';
import LearningJourneyQuestChallenges from '../../../examples/learning-journey-quest-challenges/src/example';
import LearningJourneyRegistry from '../../../examples/learning-journey-registry/src/example';
import LearningJourneyStudioOnboarding from '../../../examples/learning-journey-studio-onboarding/src/example';
import LearningJourneyUiCoaching from '../../../examples/learning-journey-ui-coaching/src/example';
import LearningJourneyUiGamified from '../../../examples/learning-journey-ui-gamified/src/example';
import LearningJourneyUiOnboarding from '../../../examples/learning-journey-ui-onboarding/src/example';
import LearningJourneyUiShared from '../../../examples/learning-journey-ui-shared/src/example';
import LearningPatterns from '../../../examples/learning-patterns/src/example';
import LifecycleCli from '../../../examples/lifecycle-cli/src/example';
import LifecycleDashboard from '../../../examples/lifecycle-dashboard/src/example';
import LocaleJurisdictionGate from '../../../examples/locale-jurisdiction-gate/src/example';
import Marketplace from '../../../examples/marketplace/src/example';
import MeetingRecorderProviders from '../../../examples/meeting-recorder-providers/src/example';
import MessagingAgentActions from '../../../examples/messaging-agent-actions/src/example';
import Minimal from '../../../examples/minimal/src/example';
import OpenbankingPowens from '../../../examples/openbanking-powens/src/example';
import OpencodeCli from '../../../examples/opencode-cli/src/example';
import Personalization from '../../../examples/personalization/src/example';
import PocketFamilyOffice from '../../../examples/pocket-family-office/src/example';
import PolicySafeKnowledgeAssistant from '../../../examples/policy-safe-knowledge-assistant/src/example';
import ProductIntent from '../../../examples/product-intent/src/example';
import ProjectManagementSync from '../../../examples/project-management-sync/src/example';
import SaasBoilerplate from '../../../examples/saas-boilerplate/src/example';
import ServiceBusinessOs from '../../../examples/service-business-os/src/example';
import TeamHub from '../../../examples/team-hub/src/example';
import VersionedKnowledgeBase from '../../../examples/versioned-knowledge-base/src/example';
import VideoApiShowcase from '../../../examples/video-api-showcase/src/example';
import VideoDocsTerminal from '../../../examples/video-docs-terminal/src/example';
import VideoMarketingClip from '../../../examples/video-marketing-clip/src/example';
import VisualizationShowcase from '../../../examples/visualization-showcase/src/example';
import VoiceProviders from '../../../examples/voice-providers/src/example';
import WealthSnapshot from '../../../examples/wealth-snapshot/src/example';
import WorkflowSystem from '../../../examples/workflow-system/src/example';

export const EXAMPLE_REGISTRY: readonly ExampleSpec[] = [
	AgentConsole,
	AiChatAssistant,
	AiSupportBot,
	AnalyticsDashboard,
	CalendarGoogle,
	ContentGeneration,
	CrmPipeline,
	DataGridShowcase,
	EmailGmail,
	InAppDocs,
	IntegrationHub,
	IntegrationPosthog,
	IntegrationStripe,
	IntegrationSupabase,
	KbUpdatePipeline,
	KnowledgeCanon,
	LearningJourneyAmbientCoach,
	LearningJourneyCrmOnboarding,
	LearningJourneyDuoDrills,
	LearningJourneyPlatformTour,
	LearningJourneyQuestChallenges,
	LearningJourneyRegistry,
	LearningJourneyStudioOnboarding,
	LearningJourneyUiCoaching,
	LearningJourneyUiGamified,
	LearningJourneyUiOnboarding,
	LearningJourneyUiShared,
	LearningPatterns,
	LifecycleCli,
	LifecycleDashboard,
	LocaleJurisdictionGate,
	Marketplace,
	MeetingRecorderProviders,
	MessagingAgentActions,
	Minimal,
	OpenbankingPowens,
	OpencodeCli,
	Personalization,
	PocketFamilyOffice,
	PolicySafeKnowledgeAssistant,
	ProductIntent,
	ProjectManagementSync,
	SaasBoilerplate,
	ServiceBusinessOs,
	TeamHub,
	VersionedKnowledgeBase,
	VideoApiShowcase,
	VideoDocsTerminal,
	VideoMarketingClip,
	VisualizationShowcase,
	VoiceProviders,
	WealthSnapshot,
	WorkflowSystem,
];
