// Generated by scripts/generate-example-registry.ts. Do not edit manually.

export interface GeneratedInlineExamplePreviewMetadata {
	key: string;
	exportName: string;
}

export const INLINE_EXAMPLE_PREVIEW_METADATA: readonly GeneratedInlineExamplePreviewMetadata[] =
	[
		{
			key: 'agent-console',
			exportName: 'ExecutionConsoleHost',
		},
		{
			key: 'ai-chat-assistant',
			exportName: 'AiChatAssistantDashboard',
		},
		{
			key: 'analytics-dashboard',
			exportName: 'AnalyticsDashboard',
		},
		{
			key: 'crm-pipeline',
			exportName: 'CrmDashboard',
		},
		{
			key: 'data-grid-showcase',
			exportName: 'DataGridShowcase',
		},
		{
			key: 'form-showcase',
			exportName: 'FormShowcasePreview',
		},
		{
			key: 'in-app-docs',
			exportName: 'InAppDocsViewer',
		},
		{
			key: 'integration-hub',
			exportName: 'IntegrationDashboard',
		},
		{
			key: 'learning-journey-registry',
			exportName: 'LearningMiniApp',
		},
		{
			key: 'marketplace',
			exportName: 'MarketplaceDashboard',
		},
		{
			key: 'policy-safe-knowledge-assistant',
			exportName: 'PolicySafeKnowledgeAssistantDashboard',
		},
		{
			key: 'saas-boilerplate',
			exportName: 'SaasDashboard',
		},
		{
			key: 'visualization-showcase',
			exportName: 'VisualizationShowcase',
		},
		{
			key: 'workflow-system',
			exportName: 'WorkflowDashboard',
		},
	];
