import * as React from 'react';
import { CheckCircle2, Circle } from 'lucide-react';

export interface Recommendation {
  id: string;
  title: string;
  description?: string;
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
  category?: string;
  completed?: boolean;
}

export interface RecommendationsListProps {
  items: Recommendation[];
  onToggle?: (id: string, completed: boolean) => void;
}

const tone: Record<Recommendation['priority'], string> = {
  HIGH: 'bg-red-500/10 text-red-500 border-red-500/50',
  MEDIUM: 'bg-amber-500/10 text-amber-500 border-amber-500/40',
  LOW: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/40',
};

export function RecommendationsList({
  items,
  onToggle,
}: RecommendationsListProps) {
  return (
    <div className="border-border bg-card space-y-3 rounded-2xl border p-4">
      <header>
        <p className="text-sm font-semibold tracking-wide uppercase">
          Recommendations
        </p>
        <p className="text-muted-foreground text-sm">
          Actionable guidance generated by the lifecycle assessments.
        </p>
      </header>
      <div className="space-y-2">
        {items.length ? (
          items.map((item) => (
            <button
              key={item.id}
              type="button"
              className="w-full text-left"
              onClick={() => onToggle?.(item.id, !item.completed)}
            >
              <div
                className={`flex items-start gap-3 rounded-xl border px-4 py-3 ${
                  item.completed
                    ? 'border-emerald-500/40 bg-emerald-500/5'
                    : 'border-border bg-background'
                }`}
              >
                <div className="mt-1">
                  {item.completed ? (
                    <CheckCircle2 className="h-5 w-5 text-emerald-500" />
                  ) : (
                    <Circle className="text-muted-foreground h-5 w-5" />
                  )}
                </div>
                <div className="flex-1 space-y-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <p className="text-sm font-semibold">{item.title}</p>
                    <span
                      className={`inline-flex rounded-full border px-2 py-0.5 text-xs font-semibold tracking-wide uppercase ${tone[item.priority]}`}
                    >
                      {item.priority}
                    </span>
                    {item.category && (
                      <span className="text-muted-foreground text-xs">
                        {item.category}
                      </span>
                    )}
                  </div>
                  {item.description && (
                    <p className="text-muted-foreground text-xs">
                      {item.description}
                    </p>
                  )}
                </div>
              </div>
            </button>
          ))
        ) : (
          <div className="text-muted-foreground border-border rounded-xl border border-dashed p-6 text-center text-sm">
            No recommendations yet. Run an assessment to populate this list.
          </div>
        )}
      </div>
    </div>
  );
}
