import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

interface ExamplePackageInfo {
	directory: string;
	packageName: string;
}

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..');
const examplesDir = path.join(repoRoot, 'packages', 'examples');
const builtinsPath = path.join(
	repoRoot,
	'packages',
	'modules',
	'examples',
	'src',
	'builtins.ts'
);

async function main(): Promise<void> {
	const write = process.argv.includes('--write');
	const packages = await discoverWorkspaceExamples();
	const rendered = renderBuiltins(packages);
	const current = await readFileIfExists(builtinsPath);

	if (!write) {
		if (current !== rendered) {
			console.error(
				`Example registry is out of date: ${path.relative(repoRoot, builtinsPath)}`
			);
			process.exitCode = 1;
		}
		return;
	}

	if (current !== rendered) {
		await fs.writeFile(builtinsPath, rendered, 'utf8');
		console.log(
			`Updated ${path.relative(repoRoot, builtinsPath)} with ${packages.length} examples.`
		);
		return;
	}

	console.log(
		`Example registry already up to date (${packages.length} examples).`
	);
}

async function discoverWorkspaceExamples(): Promise<ExamplePackageInfo[]> {
	const entries = await fs.readdir(examplesDir, { withFileTypes: true });
	const packages: ExamplePackageInfo[] = [];

	for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
		if (!entry.isDirectory()) continue;

		const packageJsonPath = path.join(examplesDir, entry.name, 'package.json');
		const pkg = await readJson<{
			name?: string;
			private?: boolean;
			exports?: Record<string, unknown>;
		}>(packageJsonPath);

		if (!pkg?.name?.startsWith('@contractspec/example.')) continue;
		if (pkg.private === true) continue;
		if (!pkg.exports?.['./example']) continue;
		if (!pkg.exports?.['./docs']) continue;

		packages.push({
			directory: entry.name,
			packageName: pkg.name,
		});
	}

	return packages.sort((a, b) => a.packageName.localeCompare(b.packageName));
}

function renderBuiltins(packages: ExamplePackageInfo[]): string {
	const lines: string[] = [
		'import type { ExampleSpec } from "@contractspec/lib.contracts-spec/examples/types";',
		'',
		'// Generated by scripts/generate-example-registry.ts. Do not edit manually.',
	];

	for (const pkg of packages) {
		lines.push(
			`import ${toIdentifier(pkg.directory)} from \"../../../examples/${pkg.directory}/src/example\";`
		);
	}

	lines.push('', 'export const EXAMPLE_REGISTRY: readonly ExampleSpec[] = [');

	for (const pkg of packages) {
		lines.push(`  ${toIdentifier(pkg.directory)},`);
	}

	lines.push('];', '');
	return `${lines.join('\n')}`;
}

function toIdentifier(value: string): string {
	const raw = value
		.split(/[^a-zA-Z0-9]+/)
		.filter(Boolean)
		.map((segment) => segment[0]!.toUpperCase() + segment.slice(1))
		.join('');

	return /^[0-9]/.test(raw) ? `Example${raw}` : raw;
}

async function readJson<T>(filePath: string): Promise<T | null> {
	try {
		const raw = await fs.readFile(filePath, 'utf8');
		return JSON.parse(raw) as T;
	} catch {
		return null;
	}
}

async function readFileIfExists(filePath: string): Promise<string | null> {
	try {
		return await fs.readFile(filePath, 'utf8');
	} catch {
		return null;
	}
}

void main();
