import { promises as fs } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

interface ExamplePackageInfo {
	directory: string;
	packageName: string;
	hasUiExport: boolean;
}

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, '..');
const examplesDir = path.join(repoRoot, 'packages', 'examples');
const builtinsPath = path.join(
	repoRoot,
	'packages',
	'modules',
	'examples',
	'src',
	'builtins.ts'
);
const previewsPath = path.join(
	repoRoot,
	'packages',
	'modules',
	'examples',
	'src',
	'runtime',
	'previews.generated.ts'
);

const PRIMARY_UI_EXPORT_BY_DIRECTORY: Record<string, string> = {
	'agent-console': 'ExecutionConsoleHost',
	'ai-chat-assistant': 'AiChatAssistantDashboard',
	'analytics-dashboard': 'AnalyticsDashboard',
	'crm-pipeline': 'CrmDashboard',
	'data-grid-showcase': 'DataGridShowcase',
	'in-app-docs': 'InAppDocsViewer',
	'integration-hub': 'IntegrationDashboard',
	'learning-journey-registry': 'LearningMiniApp',
	marketplace: 'MarketplaceDashboard',
	'policy-safe-knowledge-assistant': 'PolicySafeKnowledgeAssistantDashboard',
	'saas-boilerplate': 'SaasDashboard',
	'visualization-showcase': 'VisualizationShowcase',
	'workflow-system': 'WorkflowDashboard',
};

async function main(): Promise<void> {
	const write = process.argv.includes('--write');
	const packages = await discoverWorkspaceExamples();
	const renderedBuiltins = renderBuiltins(packages);
	const renderedPreviews = renderPreviewRegistry(packages);
	const currentBuiltins = await readFileIfExists(builtinsPath);
	const currentPreviews = await readFileIfExists(previewsPath);

	if (!write) {
		if (currentBuiltins !== renderedBuiltins) {
			console.error(
				`Example registry is out of date: ${path.relative(repoRoot, builtinsPath)}`
			);
			process.exitCode = 1;
		}
		if (currentPreviews !== renderedPreviews) {
			console.error(
				`Example preview registry is out of date: ${path.relative(
					repoRoot,
					previewsPath
				)}`
			);
			process.exitCode = 1;
		}
		return;
	}

	if (currentBuiltins !== renderedBuiltins) {
		await fs.writeFile(builtinsPath, renderedBuiltins, 'utf8');
		console.log(
			`Updated ${path.relative(repoRoot, builtinsPath)} with ${packages.length} examples.`
		);
	}

	if (currentPreviews !== renderedPreviews) {
		await fs.writeFile(previewsPath, renderedPreviews, 'utf8');
		console.log(
			`Updated ${path.relative(repoRoot, previewsPath)} with inline preview loaders.`
		);
	}

	if (
		currentBuiltins === renderedBuiltins &&
		currentPreviews === renderedPreviews
	) {
		console.log(
			`Example registry already up to date (${packages.length} examples).`
		);
	}
}

async function discoverWorkspaceExamples(): Promise<ExamplePackageInfo[]> {
	const entries = await fs.readdir(examplesDir, { withFileTypes: true });
	const packages: ExamplePackageInfo[] = [];

	for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
		if (!entry.isDirectory()) continue;

		const packageJsonPath = path.join(examplesDir, entry.name, 'package.json');
		const pkg = await readJson<{
			name?: string;
			private?: boolean;
			exports?: Record<string, unknown>;
		}>(packageJsonPath);

		if (!pkg?.name?.startsWith('@contractspec/example.')) continue;
		if (pkg.private === true) continue;
		if (!pkg.exports?.['./example']) continue;
		if (!pkg.exports?.['./docs']) continue;

		packages.push({
			directory: entry.name,
			packageName: pkg.name,
			hasUiExport: Boolean(pkg.exports?.['./ui']),
		});
	}

	return packages.sort((a, b) => a.packageName.localeCompare(b.packageName));
}

function renderBuiltins(packages: ExamplePackageInfo[]): string {
	const lines: string[] = [
		'// Generated by scripts/generate-example-registry.ts. Do not edit manually.',
	];

	for (const pkg of packages) {
		lines.push(
			`import ${toIdentifier(pkg.directory)} from "${pkg.packageName}/example";`
		);
	}

	lines.push(
		'import type { ExampleSpec } from "@contractspec/lib.contracts-spec/examples/types";'
	);
	lines.push('', 'export const EXAMPLE_REGISTRY: readonly ExampleSpec[] = [');

	for (const pkg of packages) {
		lines.push(`  ${toIdentifier(pkg.directory)},`);
	}

	lines.push('];', '');
	return `${lines.join('\n')}`;
}

function renderPreviewRegistry(packages: ExamplePackageInfo[]): string {
	const previewPackages = packages
		.filter((pkg) => pkg.hasUiExport)
		.map((pkg) => ({
			...pkg,
			exportName: PRIMARY_UI_EXPORT_BY_DIRECTORY[pkg.directory],
		}));

	for (const pkg of previewPackages) {
		if (!pkg.exportName) {
			throw new Error(
				`Missing primary UI export mapping for ${pkg.packageName}. Update PRIMARY_UI_EXPORT_BY_DIRECTORY in scripts/generate-example-registry.ts.`
			);
		}
	}

	const lines: string[] = [
		'// Generated by scripts/generate-example-registry.ts. Do not edit manually.',
		'',
		'export interface GeneratedInlineExamplePreviewRegistration {',
		'  key: string;',
		'  exportName: string;',
		'  loadModule: () => Promise<Record<string, unknown>>;',
		'}',
		'',
		'export const INLINE_EXAMPLE_PREVIEW_REGISTRY: readonly GeneratedInlineExamplePreviewRegistration[] = [',
	];

	for (const pkg of previewPackages) {
		lines.push('  {');
		lines.push(`    key: "${pkg.directory}",`);
		lines.push(`    exportName: "${pkg.exportName}",`);
		lines.push(`    loadModule: () => import("${pkg.packageName}/ui"),`);
		lines.push('  },');
	}

	lines.push('];', '');
	return `${lines.join('\n')}`;
}

function toIdentifier(value: string): string {
	const raw = value
		.split(/[^a-zA-Z0-9]+/)
		.filter(Boolean)
		.map((segment) => segment[0]!.toUpperCase() + segment.slice(1))
		.join('');

	return /^[0-9]/.test(raw) ? `Example${raw}` : raw;
}

async function readJson<T>(filePath: string): Promise<T | null> {
	try {
		const raw = await fs.readFile(filePath, 'utf8');
		return JSON.parse(raw) as T;
	} catch {
		return null;
	}
}

async function readFileIfExists(filePath: string): Promise<string | null> {
	try {
		return await fs.readFile(filePath, 'utf8');
	} catch {
		return null;
	}
}

void main();
