/**
 * Data views exporter - exports DataViewSpec to OpenAPI extensions.
 */
import type { DataViewRegistry } from '@contractspec/lib.contracts/data-views';
import type { GeneratedRegistryCode } from '../types';

/**
 * Exported data view structure for OpenAPI extensions.
 */
export interface ExportedDataView {
  name: string;
  version: string;
  description?: string;
  stability?: string;
  entity: string;
  kind: 'list' | 'detail' | 'table' | 'grid';
  source: {
    primary: { key: string; version: string };
    item?: { key: string; version: string };
  };
  fields: unknown[];
}

/**
 * Export data views to OpenAPI extension format.
 */
export function exportDataViews(
  registry: DataViewRegistry
): ExportedDataView[] {
  return registry.list().map((dv) => ({
    name: dv.meta.key,
    version: dv.meta.version,
    description: dv.meta.description,
    stability: dv.meta.stability,
    entity: dv.meta.entity,
    kind: dv.view.kind,
    source: dv.source,
    fields: dv.view.fields,
  }));
}

/**
 * Generate TypeScript code for data views registry.
 */
export function generateDataViewsRegistry(
  registry: DataViewRegistry
): GeneratedRegistryCode {
  const dataViews = registry.list();
  const imports = new Set<string>();
  const registrations: string[] = [];

  for (const dv of dataViews) {
    const dvVarName = dv.meta.key.replace(/\./g, '_') + `_v${dv.meta.version}`;
    imports.add(
      `import { ${dvVarName} } from './${dv.meta.key.split('.')[0]}';`
    );
    registrations.push(`  .register(${dvVarName})`);
  }

  const code = `/**
 * Auto-generated data views registry.
 * DO NOT EDIT - This file is generated by ContractSpec exporter.
 */
import { DataViewRegistry } from '@contractspec/lib.contracts/data-views';

${Array.from(imports).join('\n')}

export const dataViewsRegistry = new DataViewRegistry()
${registrations.join('\n')};
`;

  return {
    code,
    fileName: 'dataviews-registry.ts',
  };
}
