/**
 * Events exporter - exports EventSpec to OpenAPI extensions.
 */
import type { EventSpec } from '@lssm/lib.contracts';
import type { AnySchemaModel } from '@lssm/lib.schema';
import { z } from 'zod';
import type { GeneratedRegistryCode } from '../types';

type OpenApiSchemaObject = Record<string, unknown>;

/**
 * Exported event structure for OpenAPI extensions.
 */
export interface ExportedEvent {
  name: string;
  version: number;
  description?: string;
  payload: OpenApiSchemaObject | null;
  pii?: string[];
}

/**
 * Export events to OpenAPI extension format.
 */
export function exportEvents(
  events: EventSpec<AnySchemaModel>[]
): ExportedEvent[] {
  return events.map((event) => ({
    name: event.meta.key,
    version: event.meta.version,
    description: event.meta.description,
    payload: event.payload
      ? (z.toJSONSchema(event.payload.getZod()) as OpenApiSchemaObject)
      : null,
    pii: event.pii,
  }));
}

/**
 * Generate TypeScript code for events exports.
 */
export function generateEventsExports(
  events: EventSpec<AnySchemaModel>[]
): GeneratedRegistryCode {
  const eventExports: string[] = [];

  for (const event of events) {
    const eventVarName =
      event.meta.key.replace(/\./g, '_') + `_v${event.meta.version}`;
    eventExports.push(
      `export { ${eventVarName} } from './${event.meta.key.split('.')[0]}';`
    );
  }

  const code = `/**
 * Auto-generated events exports.
 * DO NOT EDIT - This file is generated by ContractSpec exporter.
 */

${eventExports.join('\n')}
`;

  return {
    code,
    fileName: 'events-exports.ts',
  };
}
