/**
 * Features exporter - exports FeatureModuleSpec to OpenAPI extensions.
 */
import type { FeatureRegistry } from '@lssm/lib.contracts';
import type { GeneratedRegistryCode } from '../types';

/**
 * Exported feature structure for OpenAPI extensions.
 */
export interface ExportedFeature {
  key: string;
  description?: string;
  owners?: string[];
  stability?: string;
  operations?: { name: string; version: number }[];
  events?: { name: string; version: number }[];
  presentations?: { name: string; version: number }[];
}

/**
 * Export features to OpenAPI extension format.
 */
export function exportFeatures(registry: FeatureRegistry): ExportedFeature[] {
  return registry.list().map((feature) => ({
    key: feature.meta.key,
    description: feature.meta.description,
    owners: feature.meta.owners,
    stability: feature.meta.stability,
    operations: feature.operations,
    events: feature.events,
    presentations: feature.presentations,
  }));
}

/**
 * Generate TypeScript code for features registry.
 */
export function generateFeaturesRegistry(
  registry: FeatureRegistry
): GeneratedRegistryCode {
  const features = registry.list();
  const imports = new Set<string>();
  const registrations: string[] = [];

  for (const feature of features) {
    const featureVarName = feature.meta.key.replace(/-/g, '_');
    imports.add(`import { ${featureVarName} } from './${feature.meta.key}';`);
    registrations.push(`  .register(${featureVarName})`);
  }

  const code = `/**
 * Auto-generated features registry.
 * DO NOT EDIT - This file is generated by ContractSpec exporter.
 */
import { FeatureRegistry } from '@lssm/lib.contracts';

${Array.from(imports).join('\n')}

export const featuresRegistry = new FeatureRegistry()
${registrations.join('\n')};
`;

  return {
    code,
    fileName: 'features-registry.ts',
  };
}
