/**
 * Presentations exporter - exports PresentationSpec to OpenAPI extensions.
 */
import type {
  PresentationDescriptorV2,
  PresentationRegistry,
} from '@lssm/lib.contracts';
import type { GeneratedRegistryCode } from '../types';

/**
 * Exported presentation structure for OpenAPI extensions.
 */
export interface ExportedPresentation {
  name: string;
  version: number;
  description?: string;
  stability?: string;
  kind: 'web_component' | 'markdown' | 'data';
  tags?: string[];
}

/**
 * Export presentations (V1) to OpenAPI extension format.
 */
export function exportPresentationsV1(
  registry: PresentationRegistry
): ExportedPresentation[] {
  return registry.list().map((pres) => ({
    name: pres.meta.name,
    version: pres.meta.version,
    description: pres.meta.description,
    stability: pres.meta.stability,
    kind: pres.content.kind,
    tags: pres.meta.tags,
  }));
}

/**
 * Exported V2 presentation structure for OpenAPI extensions.
 */
export interface ExportedPresentationV2 {
  name: string;
  version: number;
  description?: string;
  targets: string[];
  sourceType: string;
}

/**
 * Export presentations (V2) to OpenAPI extension format.
 */
export function exportPresentationsV2(
  descriptors: PresentationDescriptorV2[]
): ExportedPresentationV2[] {
  return descriptors.map((desc) => ({
    name: desc.meta.name,
    version: desc.meta.version,
    description: desc.meta.description,
    targets: desc.targets,
    sourceType: desc.source.type,
  }));
}

/**
 * Combined presentations export.
 */
export function exportPresentations(
  registry: PresentationRegistry,
  v2Descriptors?: PresentationDescriptorV2[]
): {
  v1: ExportedPresentation[];
  v2: ExportedPresentationV2[];
} {
  return {
    v1: exportPresentationsV1(registry),
    v2: v2Descriptors ? exportPresentationsV2(v2Descriptors) : [],
  };
}

/**
 * Generate TypeScript code for presentations registry.
 */
export function generatePresentationsRegistry(
  registry: PresentationRegistry
): GeneratedRegistryCode {
  const presentations = registry.list();
  const imports = new Set<string>();
  const registrations: string[] = [];

  for (const pres of presentations) {
    const presVarName =
      pres.meta.name.replace(/\./g, '_') + `_v${pres.meta.version}`;
    imports.add(
      `import { ${presVarName} } from './${pres.meta.name.split('.')[0]}';`
    );
    registrations.push(`  .register(${presVarName})`);
  }

  const code = `/**
 * Auto-generated presentations registry.
 * DO NOT EDIT - This file is generated by ContractSpec exporter.
 */
import { PresentationRegistry } from '@lssm/lib.contracts';

${Array.from(imports).join('\n')}

export const presentationsRegistry = new PresentationRegistry()
${registrations.join('\n')};
`;

  return {
    code,
    fileName: 'presentations-registry.ts',
  };
}
