/**
 * Presentations exporter - exports PresentationSpec to OpenAPI extensions.
 */
import type {
  PresentationSpec,
  PresentationRegistry,
  Stability,
} from '@contractspec/lib.contracts-spec';
import type { GeneratedRegistryCode } from '../types';

/**
 * Exported presentation structure for OpenAPI extensions.
 */
export interface ExportedPresentation {
  name: string;
  version: string;
  description: string; // Changed from description?: string;
  stability: Stability; // Changed from stability?: string;
  sourceType: 'component' | 'blocknotejs';
  targets: string[];
  tags?: string[];
}

/**
 * Export presentations to OpenAPI extension format.
 */
export function exportPresentations(
  registry: PresentationRegistry
): ExportedPresentation[] {
  return registry.list().map((pres) => ({
    name: pres.meta.key,
    version: pres.meta.version,
    description: pres.meta.description,
    stability: pres.meta.stability,
    sourceType: pres.source.type,
    targets: pres.targets,
    tags: pres.meta.tags,
  }));
}

/**
 * Export presentations from an array.
 */
export function exportPresentationsFromArray(
  descriptors: PresentationSpec[]
): ExportedPresentation[] {
  return descriptors.map((desc) => ({
    name: desc.meta.key,
    version: desc.meta.version,
    description: desc.meta.description,
    stability: desc.meta.stability,
    sourceType: desc.source.type,
    targets: desc.targets,
    tags: desc.meta.tags,
  }));
}

/**
 * Generate TypeScript code for presentations registry.
 */
export function generatePresentationsRegistry(
  registry: PresentationRegistry
): GeneratedRegistryCode {
  const presentations = registry.list();
  const imports = new Set<string>();
  const registrations: string[] = [];

  for (const pres of presentations) {
    const presVarName =
      pres.meta.key.replace(/\./g, '_') + `_v${pres.meta.version}`;
    imports.add(
      `import { ${presVarName} } from './${pres.meta.key.split('.')[0]}';`
    );
    registrations.push(`  .register(${presVarName})`);
  }

  const code = `/**
 * Auto-generated presentations registry.
 * DO NOT EDIT - This file is generated by ContractSpec exporter.
 */
import { PresentationRegistry } from '@contractspec/lib.contracts-spec';

${Array.from(imports).join('\n')}

export const presentationsRegistry = new PresentationRegistry()
${registrations.join('\n')};
`;

  return {
    code,
    fileName: 'presentations-registry.ts',
  };
}
