/**
 * Unified registries generator - combines all surface registries.
 */
import type { GeneratedRegistryCode } from '../types';

/**
 * Registry generation options.
 */
export interface RegistryGenerationOptions {
  operations?: boolean;
  events?: boolean;
  features?: boolean;
  presentations?: boolean;
  forms?: boolean;
  dataViews?: boolean;
  workflows?: boolean;
}

/**
 * Generate unified index file that exports all registries.
 */
export function generateRegistryIndex(
  options: RegistryGenerationOptions = {}
): GeneratedRegistryCode {
  const {
    operations = true,
    events = true,
    features = true,
    presentations = true,
    forms = true,
    dataViews = true,
    workflows = true,
  } = options;

  const exports: string[] = [];

  if (operations) {
    exports.push("export * from './operations-registry';");
  }
  if (events) {
    exports.push("export * from './events-exports';");
  }
  if (features) {
    exports.push("export * from './features-registry';");
  }
  if (presentations) {
    exports.push("export * from './presentations-registry';");
  }
  if (forms) {
    exports.push("export * from './forms-registry';");
  }
  if (dataViews) {
    exports.push("export * from './dataviews-registry';");
  }
  if (workflows) {
    exports.push("export * from './workflows-registry';");
  }

  const code = `/**
 * Auto-generated registry index.
 * DO NOT EDIT - This file is generated by ContractSpec exporter.
 */

${exports.join('\n')}
`;

  return {
    code,
    fileName: 'index.ts',
  };
}
