/**
 * Workflows exporter - exports WorkflowSpec to OpenAPI extensions.
 */
import type { WorkflowRegistry } from '@contractspec/lib.contracts-spec/workflow';
import type { GeneratedRegistryCode } from '../types';

/**
 * Exported workflow structure for OpenAPI extensions.
 */
export interface ExportedWorkflow {
  name: string;
  version: string;
  description?: string;
  stability?: string;
  owners?: string[];
  steps: {
    id: string;
    type: 'human' | 'automation' | 'decision';
    label: string;
  }[];
  transitions: {
    from: string;
    to: string;
    label?: string;
  }[];
}

/**
 * Export workflows to OpenAPI extension format.
 */
export function exportWorkflows(
  registry: WorkflowRegistry
): ExportedWorkflow[] {
  return registry.list().map((wf) => ({
    name: wf.meta.key,
    version: wf.meta.version,
    description: wf.meta.description,
    stability: wf.meta.stability,
    owners: wf.meta.owners,
    steps: wf.definition.steps.map((s) => ({
      id: s.id,
      type: s.type,
      label: s.label,
    })),
    transitions: wf.definition.transitions.map((t) => ({
      from: t.from,
      to: t.to,
      label: t.label,
    })),
  }));
}

/**
 * Generate TypeScript code for workflows registry.
 */
export function generateWorkflowsRegistry(
  registry: WorkflowRegistry
): GeneratedRegistryCode {
  const workflows = registry.list();
  const imports = new Set<string>();
  const registrations: string[] = [];

  for (const wf of workflows) {
    const wfVarName = wf.meta.key.replace(/\./g, '_') + `_v${wf.meta.version}`;
    imports.add(
      `import { ${wfVarName} } from './${wf.meta.key.split('.')[0]}';`
    );
    registrations.push(`  .register(${wfVarName})`);
  }

  const code = `/**
 * Auto-generated workflows registry.
 * DO NOT EDIT - This file is generated by ContractSpec exporter.
 */
import { WorkflowRegistry } from '@contractspec/lib.contracts-spec/workflow';

${Array.from(imports).join('\n')}

export const workflowsRegistry = new WorkflowRegistry()
${registrations.join('\n')};
`;

  return {
    code,
    fileName: 'workflows-registry.ts',
  };
}
