import type { ExecutionLaneSpec } from '../types';
import { DEFAULT_TRANSITIONS } from './transitions';

export const DEFAULT_LANES: ExecutionLaneSpec[] = [
	{
		key: 'clarify',
		description: 'Reduces ambiguity and produces a clarification artifact.',
		entryCriteria: ['request is ambiguous or conflicting'],
		exitCriteria: ['ambiguity score recorded', 'next lane recommended'],
		allowedTransitions: DEFAULT_TRANSITIONS.clarify,
		compatibleRoles: ['planner', 'researcher'],
		requiredArtifacts: ['clarification_artifact'],
		verificationPolicy: {
			key: 'lane.clarify',
			requiredEvidence: ['clarification_artifact'],
			minimumApprovals: [],
			failOnMissingEvidence: true,
			allowConditionalCompletion: false,
		},
		capabilities: {
			parallelism: 'none',
			persistence: 'checkpointed',
			approvals: false,
			mailbox: false,
			taskLeasing: false,
		},
	},
	{
		key: 'plan.consensus',
		description: 'Runs planner, architect, and critic to produce a plan pack.',
		entryCriteria: ['clarity sufficient to plan'],
		exitCriteria: ['plan pack approved', 'next lane justified'],
		allowedTransitions: DEFAULT_TRANSITIONS['plan.consensus'],
		compatibleRoles: ['planner', 'architect', 'critic', 'researcher'],
		requiredArtifacts: [
			'plan_pack',
			'architect_review',
			'critique_verdict',
			'tradeoff_record',
		],
		verificationPolicy: {
			key: 'lane.plan.consensus',
			requiredEvidence: [
				'plan_pack',
				'architect_review',
				'critique_verdict',
				'tradeoff_record',
			],
			minimumApprovals: [],
			failOnMissingEvidence: true,
			allowConditionalCompletion: false,
		},
		capabilities: {
			parallelism: 'bounded',
			persistence: 'checkpointed',
			approvals: true,
			mailbox: false,
			taskLeasing: false,
		},
	},
	{
		key: 'complete.persistent',
		description: 'Runs a durable single-owner completion loop.',
		entryCriteria: ['plan pack available'],
		exitCriteria: ['evidence satisfied', 'signoff complete'],
		allowedTransitions: DEFAULT_TRANSITIONS['complete.persistent'],
		compatibleRoles: ['executor', 'verifier', 'architect', 'test-engineer'],
		requiredArtifacts: [
			'completion_record',
			'progress_ledger',
			'signoff_record',
		],
		verificationPolicy: {
			key: 'lane.complete.persistent',
			requiredEvidence: ['progress_ledger', 'verification_results'],
			minimumApprovals: [{ role: 'verifier', verdict: 'approve' }],
			failOnMissingEvidence: true,
			allowConditionalCompletion: false,
		},
		capabilities: {
			parallelism: 'bounded',
			persistence: 'durable',
			approvals: true,
			mailbox: false,
			taskLeasing: false,
		},
	},
	{
		key: 'team.coordinated',
		description: 'Runs coordinated multi-worker execution with leases.',
		entryCriteria: ['plan pack available', 'parallel fanout justified'],
		exitCriteria: ['tasks terminal', 'shutdown policy passes'],
		allowedTransitions: DEFAULT_TRANSITIONS['team.coordinated'],
		compatibleRoles: ['executor', 'verifier', 'test-engineer', 'writer'],
		requiredArtifacts: [
			'team_snapshot',
			'verification_lane_evidence',
			'team_cleanup_state',
		],
		verificationPolicy: {
			key: 'lane.team.coordinated',
			requiredEvidence: ['verification_results'],
			minimumApprovals: [],
			failOnMissingEvidence: true,
			allowConditionalCompletion: true,
		},
		capabilities: {
			parallelism: 'durable',
			persistence: 'durable',
			approvals: true,
			mailbox: true,
			taskLeasing: true,
		},
	},
];
