import type { RoleProfile } from '../types';

export const DEFAULT_ROLE_PROFILES: RoleProfile[] = [
	{
		key: 'planner',
		description: 'Produces structured execution plans without implementing.',
		routingRole: 'leader',
		posture: 'orchestrator',
		allowedTools: ['read', 'analyze', 'review'],
		writeScope: 'artifacts-only',
		laneCompatibility: ['clarify', 'plan.consensus', 'team.coordinated'],
		evidenceObligations: ['plan_pack', 'tradeoff_record'],
		escalationTriggers: ['scope_conflict', 'missing_acceptance_criteria'],
		modelProfileHint: 'frontier-planner',
	},
	{
		key: 'architect',
		description: 'Checks boundaries, tradeoffs, and architecture soundness.',
		routingRole: 'specialist',
		posture: 'critic',
		allowedTools: ['read', 'analyze', 'review'],
		writeScope: 'none',
		laneCompatibility: ['plan.consensus', 'complete.persistent'],
		evidenceObligations: ['architect_review'],
		escalationTriggers: ['boundary_violation', 'policy_risk'],
		modelProfileHint: 'frontier-architect',
	},
	{
		key: 'critic',
		description: 'Rejects vague plans and incomplete verification paths.',
		routingRole: 'reviewer',
		posture: 'critic',
		allowedTools: ['read', 'analyze', 'review'],
		writeScope: 'artifacts-only',
		laneCompatibility: ['plan.consensus'],
		evidenceObligations: ['critique_verdict'],
		escalationTriggers: ['untestable_plan', 'scope_creep'],
		modelProfileHint: 'critic',
	},
	{
		key: 'executor',
		description: 'Executes implementation work in an assigned scope.',
		routingRole: 'executor',
		posture: 'builder',
		allowedTools: ['read', 'analyze', 'execute', 'review'],
		writeScope: 'workspace',
		laneCompatibility: ['complete.persistent', 'team.coordinated'],
		evidenceObligations: ['completion_record', 'verification_results'],
		escalationTriggers: ['shared_conflict', 'destructive_change'],
		modelProfileHint: 'executor',
	},
	{
		key: 'verifier',
		description: 'Owns completion gates and evidence sufficiency.',
		routingRole: 'reviewer',
		posture: 'verifier',
		allowedTools: ['read', 'analyze', 'review', 'execute'],
		writeScope: 'artifacts-only',
		laneCompatibility: ['complete.persistent', 'team.coordinated'],
		evidenceObligations: ['verification_results', 'signoff_record'],
		escalationTriggers: ['missing_evidence', 'failing_checks'],
		modelProfileHint: 'verifier',
	},
	{
		key: 'test-engineer',
		description: 'Designs and runs regression coverage.',
		routingRole: 'specialist',
		posture: 'verifier',
		allowedTools: ['read', 'analyze', 'execute', 'review'],
		writeScope: 'workspace',
		laneCompatibility: ['complete.persistent', 'team.coordinated'],
		evidenceObligations: ['verification_results'],
		escalationTriggers: ['flaky_suite', 'coverage_gap'],
		modelProfileHint: 'test-engineer',
	},
	{
		key: 'security-reviewer',
		description: 'Checks trust boundaries and policy-sensitive changes.',
		routingRole: 'specialist',
		posture: 'critic',
		allowedTools: ['read', 'analyze', 'review'],
		writeScope: 'none',
		laneCompatibility: [
			'plan.consensus',
			'complete.persistent',
			'team.coordinated',
		],
		evidenceObligations: ['architect_review'],
		escalationTriggers: ['secret_exposure', 'approval_required'],
		modelProfileHint: 'security-reviewer',
	},
	{
		key: 'researcher',
		description: 'Performs bounded read-only investigation.',
		routingRole: 'specialist',
		posture: 'researcher',
		allowedTools: ['read', 'analyze', 'network'],
		writeScope: 'none',
		laneCompatibility: ['clarify', 'plan.consensus', 'team.coordinated'],
		evidenceObligations: ['clarification_artifact'],
		escalationTriggers: ['source_conflict', 'missing_primary_source'],
		modelProfileHint: 'researcher',
	},
	{
		key: 'writer',
		description: 'Produces docs, migration notes, and operator guidance.',
		routingRole: 'specialist',
		posture: 'builder',
		allowedTools: ['read', 'analyze', 'execute', 'review'],
		writeScope: 'workspace',
		laneCompatibility: ['team.coordinated', 'complete.persistent'],
		evidenceObligations: ['completion_record'],
		escalationTriggers: ['public_api_change', 'migration_gap'],
		modelProfileHint: 'writer',
	},
];
