name: 'ContractSpec Version Manager'
description: 'Automated version bumping and changelog generation for ContractSpec workspaces'
author: 'LSSM'

inputs:
  mode:
    description: 'Action mode: analyze (check only) or bump (apply changes)'
    required: false
    default: 'analyze'
  auto-bump:
    description: 'Whether to automatically applying bumps based on impact analysis'
    required: false
    default: 'false'
  commit-message:
    description: 'Commit message for version bumps'
    required: false
    default: 'chore(release): bump spec versions [skip ci]'
  create-pr:
    description: 'Create a Pull Request instead of pushing directly'
    required: false
    default: 'false'
  pr-title:
    description: 'Title for the Pull Request'
    required: false
    default: 'chore(release): version packages'
  pr-branch:
    description: 'Branch name for the Pull Request'
    required: false
    default: 'release/next-versions'
  github-token:
    description: 'GitHub Token for creating PRs'
    required: false
    default: ${{ github.token }}
  
outputs:
  has-changes:
    description: 'Whether changes were detected/applied'
    value: ${{ steps.analysis.outputs.has-changes }}
  specs-bumped:
    description: 'Number of specs bumped'
    value: ${{ steps.analysis.outputs.specs-bumped }}

runs:
  using: "composite"
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install Dependencies
      shell: bash
      run: bun install

    - name: Build CLI (if local)
      shell: bash
      if: ${{ hashFiles('packages/apps/cli-contractspec/package.json') != '' }}
      run: |
        echo "Building local CLI..."
        cd packages/apps/cli-contractspec && bun run build
        echo "CLI_PATH=$(pwd)/dist/index.js" >> $GITHUB_ENV

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Analyze Versions
      id: analysis
      shell: bash
      if: ${{ inputs.mode == 'analyze' }}
      run: |
        if [ -n "$CLI_PATH" ]; then
          bun run $CLI_PATH version analyze --format json > analysis.json
        else
          bunx @lssm/app.cli-contractspec version analyze --format json > analysis.json
        fi
        
        COUNT=$(jq '.specsNeedingBump' analysis.json)
        echo "specs-bumped=$COUNT" >> $GITHUB_OUTPUT
        if [ "$COUNT" -gt "0" ]; then
          echo "has-changes=true" >> $GITHUB_OUTPUT
        else
          echo "has-changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Bump Versions
      id: bump
      shell: bash
      if: ${{ inputs.mode == 'bump' }}
      run: |
        ARGS=""
        if [ "${{ inputs.auto-bump }}" == "true" ]; then
          ARGS="--all --yes"
        else
          # If not auto, we assume manual inputs or interactive (which doesn't work in CI usually, unless with inputs)
          # For CI action, we default to --all if mode is bump
          ARGS="--all --yes"
        fi

        if [ -n "$CLI_PATH" ]; then
          bun run $CLI_PATH version bump $ARGS
          bun run $CLI_PATH changelog generate
        else
          bunx @lssm/app.cli-contractspec version bump $ARGS
          bunx @lssm/app.cli-contractspec changelog generate
        fi

    - name: Create Pull Request
      if: ${{ inputs.mode == 'bump' && inputs.create-pr == 'true' }}
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        git checkout -b ${{ inputs.pr-branch }}
        git add .
        git commit -m "${{ inputs.commit-message }}" || echo "No changes to commit"
        git push origin ${{ inputs.pr-branch }} --force
        gh pr create --title "${{ inputs.pr-title }}" --body "Automated version bumps generated by ContractSpec." --base main --head ${{ inputs.pr-branch }} || echo "PR already exists"

    - name: Commit Direct
      if: ${{ inputs.mode == 'bump' && inputs.create-pr == 'false' }}
      shell: bash
      run: |
        git add .
        git commit -m "${{ inputs.commit-message }}" || echo "No changes to commit"
        git push origin HEAD
