name: 'ContractSpec CI'
description: 'Run ContractSpec validation checks in your CI/CD pipeline'
author: 'LSSM'
branding:
  icon: 'check-circle'
  color: 'blue'

inputs:
  checks:
    description: 'Checks to run (comma-separated: structure,integrity,deps,doctor,handlers,tests) or "all"'
    required: false
    default: 'all'
  skip:
    description: 'Checks to skip (comma-separated)'
    required: false
    default: ''
  pattern:
    description: 'Glob pattern for spec discovery'
    required: false
    default: ''
  fail-on-warnings:
    description: 'Fail the action on warnings (not just errors)'
    required: false
    default: 'false'
  check-handlers:
    description: 'Include handler implementation checks'
    required: false
    default: 'false'
  check-tests:
    description: 'Include test coverage checks'
    required: false
    default: 'false'
  upload-sarif:
    description: 'Upload SARIF results to GitHub Code Scanning'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for running checks'
    required: false
    default: '.'
  bun-version:
    description: 'Bun version to use'
    required: false
    default: 'latest'

outputs:
  success:
    description: 'Whether all checks passed'
  errors:
    description: 'Number of errors found'
  warnings:
    description: 'Number of warnings found'
  sarif-file:
    description: 'Path to SARIF output file (if uploaded)'
  json-file:
    description: 'Path to JSON output file'

runs:
  using: 'composite'
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ inputs.bun-version }}

    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ -f "bun.lock" ] || [ -f "bun.lockb" ]; then
          bun install --frozen-lockfile
        elif [ -f "package-lock.json" ]; then
          npm ci
        elif [ -f "pnpm-lock.yaml" ]; then
          corepack enable
          pnpm install --frozen-lockfile
        elif [ -f "yarn.lock" ]; then
          corepack enable
          yarn install --frozen-lockfile
        else
          bun install
        fi

    - name: Build ContractSpec CLI (if local)
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        # Check if this is the ContractSpec monorepo itself
        if [ -f "packages/apps/cli-contracts/package.json" ]; then
          echo "Building ContractSpec CLI from source..."
          bun run build --filter=@lssm/app.cli-contracts
        fi

    - name: Run ContractSpec CI checks
      id: ci-checks
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        CHECKS: ${{ inputs.checks }}
        SKIP: ${{ inputs.skip }}
        PATTERN: ${{ inputs.pattern }}
        FAIL_ON_WARNINGS: ${{ inputs.fail-on-warnings }}
        CHECK_HANDLERS: ${{ inputs.check-handlers }}
        CHECK_TESTS: ${{ inputs.check-tests }}
      run: |
        # Build command arguments
        ARGS=""

        if [ "$CHECKS" != "all" ] && [ -n "$CHECKS" ]; then
          ARGS="$ARGS --checks $CHECKS"
        fi

        if [ -n "$SKIP" ]; then
          ARGS="$ARGS --skip $SKIP"
        fi

        if [ -n "$PATTERN" ]; then
          ARGS="$ARGS --pattern '$PATTERN'"
        fi

        if [ "$FAIL_ON_WARNINGS" = "true" ]; then
          ARGS="$ARGS --fail-on-warnings"
        fi

        if [ "$CHECK_HANDLERS" = "true" ]; then
          ARGS="$ARGS --check-handlers"
        fi

        if [ "$CHECK_TESTS" = "true" ]; then
          ARGS="$ARGS --check-tests"
        fi

        # Create output directory
        mkdir -p .contractspec-ci

        # Run checks and capture JSON output
        echo "Running: contractspec ci --format json $ARGS"
        set +e
        npx contractspec ci --format json $ARGS > .contractspec-ci/results.json 2>&1
        EXIT_CODE=$?
        set -e

        # Parse results for outputs
        if [ -f ".contractspec-ci/results.json" ]; then
          SUCCESS=$(jq -r '.success' .contractspec-ci/results.json 2>/dev/null || echo "false")
          ERRORS=$(jq -r '.summary.totalErrors // .errors // 0' .contractspec-ci/results.json 2>/dev/null || echo "0")
          WARNINGS=$(jq -r '.summary.totalWarnings // .warnings // 0' .contractspec-ci/results.json 2>/dev/null || echo "0")

          echo "success=$SUCCESS" >> $GITHUB_OUTPUT
          echo "errors=$ERRORS" >> $GITHUB_OUTPUT
          echo "warnings=$WARNINGS" >> $GITHUB_OUTPUT
          echo "json-file=.contractspec-ci/results.json" >> $GITHUB_OUTPUT
        else
          echo "success=false" >> $GITHUB_OUTPUT
          echo "errors=1" >> $GITHUB_OUTPUT
          echo "warnings=0" >> $GITHUB_OUTPUT
        fi

        # Generate SARIF for upload
        if [ "${{ inputs.upload-sarif }}" = "true" ]; then
          echo "Generating SARIF output..."
          npx contractspec ci --format sarif $ARGS > .contractspec-ci/results.sarif 2>/dev/null || true
          echo "sarif-file=.contractspec-ci/results.sarif" >> $GITHUB_OUTPUT
        fi

        # Print text summary
        echo ""
        echo "=== ContractSpec CI Results ==="
        npx contractspec ci --format text $ARGS 2>/dev/null || true

        exit $EXIT_CODE

    - name: Upload SARIF to GitHub Code Scanning
      if: inputs.upload-sarif == 'true' && always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: ${{ inputs.working-directory }}/.contractspec-ci/results.sarif
        category: contractspec
      continue-on-error: true

    - name: Upload results as artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: contractspec-ci-results
        path: |
          ${{ inputs.working-directory }}/.contractspec-ci/results.json
          ${{ inputs.working-directory }}/.contractspec-ci/results.sarif
        retention-days: 30
      continue-on-error: true





